### ISSUE TITLE
Error When Uploading 

### ISSUE THREAD

**Issue by tahafathi2013** [board707/DMD_STM32#100]
hi
i have Error when uploading code 
how fix it?

Sketch uses 30784 bytes (46%) of program storage space. Maximum is 65536 bytes.
Global variables use 2776 bytes (13%) of dynamic memory, leaving 17704 bytes for local variables. Maximum is 20480 bytes.
Got NACK from device on command 0xff
stm32flash 0.4
Failed to erase memory

http://stm32flash.googlecode.com/

Using Parser : Raw BINARY
Interface serial_w32: 115200 8E1
Version      : 0x30
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0410 (Medium-density)
- RAM        : 20KiB  (512b reserved by bootloader)
- Flash      : 128KiB (sector size: 4x1024)
- Option RAM : 16b
- System RAM : 2KiB
Write to memory
Erasing memory

**Comment by board707** [comment]
> stm32flash 0.4

Hi, I have no expediency with this program.

> Failed to erase memory

Your problem hardly has anything to do with the library.
