### ISSUE TITLE
Add a new panel 80x40 s10 ShiftReg DP5125D RUL5158C

### ISSUE THREAD

**Issue by ShiPC123** [board707/DMD_STM32#104]
## Panel photos

![0e57608137b5bd6828393187de733274](https://github.com/board707/DMD_STM32/assets/132763025/732ffcd2-cd0e-4c66-94ff-4b0217bf9d52)
![77478e53bd9b6693ab7ceb076ea94a60](https://github.com/board707/DMD_STM32/assets/132763025/86fc0090-31cb-4c99-b1a4-45282c4ece14)

## Specifications

  - Library version: 1.1.4
  - Platform: STM32
  - MCU board: blackpil STM32F103RCT6
  - Connections: CLK  --  PA0   R0 --PA1  G0 --PA2  B0 --PA3   R1 --PA4  G1 --PA5  B1 --PA6  OE --PB0  LAT--PB1  A--PB15 B--PB14 C--PB13  D--PB12

**Comment by ShiPC123** [comment]
I run the test code  Interface and MCU options are shown 
![企业微信截图_17143610018579](https://github.com/board707/DMD_STM32/assets/132763025/2e770022-360c-40dd-b599-72f175c76c27)
![企业微信截图_17143610835618](https://github.com/board707/DMD_STM32/assets/132763025/67b5c249-48f8-422d-ad98-0465ddc2451b)
![e558f341dbca84a675f9b0c8354b5601](https://github.com/board707/DMD_STM32/assets/132763025/86eee068-3281-47fe-bb75-ce9e76b110e6)

**Comment by board707** [comment]
Hi
According with paper label on the panel, it used RUL5158C as multiplexor. This chip seems to be shift register type, so you need to use `DMD_RGB_SHIFTREG_ABC` class rather than `DMD_RGB`.

Add define below at the start of the sketch:
`#define RGB80x40_S10_ShiPC123 3,80,40,10,2`

Add setup the DMD class as
```
DMD_RGB_SHIFTREG_ABC <RGB80x40_S10_ShiPC123, COLOR_4BITS_Packed> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
```
Run the `pattern_test` example with editions, mentioned above and show the video.

**Comment by ShiPC123** [comment]
I ran the example, and the display screen was displayed in four places, the upper left corner was 1, the upper right corner was 2, the lower left corner was 3, the right small corner was 4, and the display sequence was 1-2-3-4
![838cf9c1795ab2ffe4a510159297180b](https://github.com/board707/DMD_STM32/assets/132763025/582ba784-027c-4f67-9044-3b62fcbb99a7)

**Comment by ShiPC123** [comment]
https://github.com/board707/DMD_STM32/assets/132763025/c4342f96-e5ed-4fce-bf4b-8fcb6e371bfc

**Comment by ShiPC123** [comment]
If I use the following parameters #define RGB80x40_S10_ShiPC123 3,80,40,10,1
The display effect is as follows

https://github.com/board707/DMD_STM32/assets/132763025/c5dd10b5-355d-4b00-9a6f-f198e284debd

**Comment by board707** [comment]
@ShiPC123 
Thank you for your tests. 

Please try the same code with pattern:
`#define RGB80x40_S10_ShiPC123 3,80,40,10,101,4,PATTERN_UPS`

**Comment by ShiPC123** [comment]
Hello， code encountered an error
<img width="1112" alt="4605c8e3e7845f9332b26fac039a136" src="https://github.com/board707/DMD_STM32/assets/132763025/28e51670-00df-4241-ad99-8ab69611931c">

**Comment by ShiPC123** [comment]
class DMD_RGB_SHIFTREG_ABC : public DMD_RGB<MUX_CNT, P_Width, P_Height, SCAN, SCAN_TYPE, COL_DEPTH>

Only 6 arguments can be passed in a function

**Comment by board707** [comment]
O... sorry for this mistake.
Please replace the file `DMD_Panel_Templates.h` in the library to the file from archive, attached to the message.

[DMD_Panel_Templates.zip](https://github.com/board707/DMD_STM32/files/15217423/DMD_Panel_Templates.zip)

**Comment by ShiPC123** [comment]
Hi, I tested #define RGB80x40_S10_ShiPC123, 3,80,40,10,101,4,PATTERN_UPS

Results like video

https://github.com/board707/DMD_STM32/assets/132763025/99e2096e-551a-494a-905c-78af11622976

**Comment by board707** [comment]
Thank you
try this
`#define RGB80x40_S10_ShiPC123, 3,80,40,10,102,4,PATTERN_UPS`

**Comment by ShiPC123** [comment]
Thank you very much ,that the display is now working ,Thank you. Thank you

**Comment by board707** [comment]
Thanks for your feedback.
I will add the new pattern to the main library and let you know so you could use it without editing the library.

**Comment by board707** [comment]
New pattern added.
Your can use it as any other library pattern, without additional definition:
`DMD_RGB_SHIFTREG_ABC <RGB80x40_S10_ShiPC123, COLOR_4BITS> dmd(mux_list....`
