### ISSUE TITLE
STM32F407VGT6 + 32*16 (hub12) mono LED panel

### ISSUE THREAD

**Issue by MMB923** [board707/DMD_STM32#109]
## Panel description 
Hello Guys
I've used a library to run P10 LED Panel using a ST discovery board and it was successful.
As you guys see, the text is not as clear as it should be so I think there is a problem with refreshing part, As you see in video and picture attached. Can you guys help me for it?
P.S: All the libraries that I found are based on #include "Arduino.h" which is not fit with my hardware; so, the library should be based on "hal.h"
Thanks.
## Panel photos

https://github.com/board707/DMD_STM32/assets/38404466/482854a5-d56e-4ebb-a1ef-cbd0b90c5e65

![1](https://github.com/board707/DMD_STM32/assets/38404466/0e950661-3bd4-4dd6-a98c-d03f4d51872e)

/board707/DMD_STM32/assets/3

## Specifications

  - Library version: 1.01
  - Platform: STM32
  - MCU board: Discovery F4
  - Connections: used pins

**Comment by MMB923** [comment]
@board707

**Comment by board707** [comment]
Is this panel a monochrome or RGB? I am not hear about Monochrome ones with 1/32 scan

> All the libraries that I found are based on #include "Arduino.h" which is not fit with my hardware;

As far as I know, the Discovery F4 can be used with Arduino. If you are ready to use Arduino code - we could try to run with your panel.
If this is not suited for you - I am sorry, I will not be able to help you

**Comment by MMB923** [comment]
@board707 
Yes, it is a monochrome and about the scan rate, I made a mistake.
if it is possible to use Arduino code for discovery, please go ahead. I want to use it as well
Thanks

**Comment by board707** [comment]
> if it is possible to use Arduino code for discovery, please go ahead. I want to use it as well

Yes, I hope it will work.

1.Please read the [Installation](https://github.com/board707/DMD_STM32/tree/dev-V2#installation) section in the library Readme. You first need to install the Arduino_STM32 package by Roger Clark, Adafruit_GFX library and then DMD_STM32 library.

2. Run an Arduino IDE, Tools menu and select "STM32 Discovery F407" board. Open a DMD_STM32 example `examples/STM32F4_RP2040/dmd_monochrome` and try to compile. 

If it compiled without errors, it means that you installation was successfull and we can to continue...

**Comment by MMB923** [comment]
Thanks for your help, but it is too complicated and I need some help. I don't know how to install STM32 and I prefer to use cube IDE instead of Arduino.

**Comment by board707** [comment]
Sorry, I didn't use a CubeIDE with my library and hardly can help you with it.

As about Installation of Arduino_STM32 - you can find a detailed guide there: https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation
If you have any questions, please feel free to ask.

**Comment by MMB923** [comment]
This one was very useful, but still I have no idea how to program it.
I use UART to program my processor, but there is no .elf file for it

**Comment by board707** [comment]
Did you install the core? Try to compile any example.
If succeed, than you need to install Adafruit_GFX library and DMD_STM32 library.

> I have no idea how to program it.

Hmmm...
Do you mean you don't know how to program Arduino or how to program at all?  In any way, once we'll install the library and will able to work - you will need to program the code for the panel itself. The library is not a user level product, it is for developing purpose.
What is your programming experience?

**Comment by MMB923** [comment]
> Do you mean you don't know how to program Arduino or how to program at all?

I mean I'm using an Arduino file in order to program a ST Discovery board; That's that I don't know.

and about the Libraries, I've installed DMD_STM32 and Adafruit_GFX libraries

**Comment by board707** [comment]
> I've installed DMD_STM32 

Run an Arduino IDE, Tools menu and select "STM32 Discovery F407" board. Open a DMD_STM32 example examples/STM32F4_RP2040/dmd_monochrome and try to compile.

**Comment by MMB923** [comment]
> > I've installed DMD_STM32
> 
> Run an Arduino IDE, Tools menu and select "STM32 Discovery F407" board. Open a DMD_STM32 example examples/STM32F4_RP2040/dmd_monochrome and try to compile.

![image](https://github.com/board707/DMD_STM32/assets/38404466/7988990c-4cb5-4ac3-83e3-1a10fc4f603b)

**Comment by board707** [comment]
It's seems that you missed a second point of [Arduino_STM32 installation](https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation):

> Run the IDE, and on the Tools menu, select the Boards manager, and install the Arduino SAM boards (Cortex-M3) from the list of available boards. You must do this step, it installs the arm-none-eabi-g++ toolchain!

**Comment by MMB923** [comment]
> missed a second point

I see. That's true. I'm installing it now. I'll inform you the update

**Comment by MMB923** [comment]
> It's seems that you missed a second point of [Arduino_STM32 installation](https://github.com/rogerclarkmelbourne/Arduino_STM32/wiki/Installation):
> 
> > Run the IDE, and on the Tools menu, select the Boards manager, and install the Arduino SAM boards (Cortex-M3) from the list of available boards. You must do this step, it installs the arm-none-eabi-g++ toolchain!

now it is done. So, should I have an Arduino to use it as a programmer for my PCB or is it available to get any output file in .bin or .elf shape?

**Comment by board707** [comment]
You could use a St-link to download the code. 
You also can use a firmware as .elf or .bin file. In order to find this files after compiling locate the line in Arduino compiler output that referred to `arm-none-eabi-objcopy`:
```
/home/user/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-objcopy -O binary /tmp/arduino_build_461166/dmd_monochrome.ino.elf /tmp/arduino_build_461166/dmd_monochrome.ino.bin
```
it point you to the temporary build folder with output files

**Comment by MMB923** [comment]
> You could use a St-link to download the code. You also can use a firmware as .elf or .bin file. In order to find this files after compiling locate the line in Arduino compiler output that referred to `arm-none-eabi-objcopy`:
> 
> ```
> /home/user/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-objcopy -O binary /tmp/arduino_build_461166/dmd_monochrome.ino.elf /tmp/arduino_build_461166/dmd_monochrome.ino.bin
> ```
> 
> it point you to the temporary build folder with output files

Thank you.
Just another question. As I told you before, I'm using ArduinoIDE without any Arduino hardware and I wanna program a ST processor; So, All the pin assignments should be according to to A ST processor and it is not available!!
See here:

![image](https://github.com/board707/DMD_STM32/assets/38404466/90a89530-c82d-4847-9b27-3c968d24dcaf)


![image](https://github.com/board707/DMD_STM32/assets/38404466/a60c60d1-4bf1-4659-928f-b4c09f1abaf1)

**Comment by board707** [comment]
According to the picture, you get an example for RP2040 board and not for STM32.

The pins for STM32 looks like:
```
#define DMD_PIN_A PA1
#define DMD_PIN_B PA4
#define DMD_PIN_nOE PB1
#define DMD_PIN_SCLK PA15
```
Are Discovery pins labelled other that in form "PA3" or "PC11" ?

**Comment by MMB923** [comment]
> According to the picture, you get an example for RP2040 board and not for STM32.
> 
> The pins for STM32 looks like:
> 
> ```
> #define DMD_PIN_A PA1
> #define DMD_PIN_B PA4
> #define DMD_PIN_nOE PB1
> #define DMD_PIN_SCLK PA15
> ```
> 
> Are Discovery pins labelled other that in form "PA3" or "PC11" ?

![image](https://github.com/board707/DMD_STM32/assets/38404466/078fe821-0060-4cdb-9a3c-52eedfef5656)

![image](https://github.com/board707/DMD_STM32/assets/38404466/97c0b5a0-3a3a-4451-a179-47c0913c6dd0)

All the examples that I have is visible in these pictures.
Actually I use STM32F405RGT6 on a PCB that I made. any change is needed for it? All F4 series are the same in programming

**Comment by board707** [comment]
> All the examples that I have is visible in these pictures.

You have to use "DMD_STM32" library, and example `STM32F4_RP2040/dmd_monochrome` The pin names are in the example inside conditional compilation directivas for `__STM32F4__`. If you have a problems to find the pin numbers - I will write it for you.

> Actually I use STM32F405RGT6 

Let's try to begin with "STM32 Discovery F407" board.

**Comment by MMB923** [comment]
> > All the examples that I have is visible in these pictures.
> 
> You have to use "DMD_STM32" library, and example `STM32F4_RP2040/dmd_monochrome` The pin names are in the example inside conditional compilation directivas for `__STM32F4__`. If you have a problems to find the pin numbers - I will write it for you.
> 
> > Actually I use STM32F405RGT6
> 
> Let's try to begin with "STM32 Discovery F407" board.

It's OK. But I don't have discovery now. Just My PCB, Bluepill and Arduino are available for now.
Maybe I can Use F1 Bluepill now, then change it to F4?

**Comment by board707** [comment]
Of course try with bluepill

**Comment by MMB923** [comment]
> Of course try with bluepill

Not working bro :(

**Comment by board707** [comment]
Please show more details about your tests. Show your code and all connections
