### ISSUE TITLE
Joining the panels (DISPLAYS_ACROSS = 2, DISPLAYS_DOWN = 2)

### ISSUE THREAD

**Issue by impuls-op** [board707/DMD_STM32#126]
I want to connect 4 panels (2x2)
DISPLAYS_ACROSS = 2
DISPLAYS_DOWN = 2

I know that the panels can be connected in a simple way like my firsts photo.
But need a long cable between second and third panels. 

![1725018576349](https://github.com/user-attachments/assets/732fcd4d-cbe1-43f4-9ffc-b017b0e62bdd)

if i turn the second row the cable between second and third panels will be short. 
But the image of the second row will be inverted. Can this be set somewhere in the config?

![1725018673503](https://github.com/user-attachments/assets/c47934fa-dd36-44f5-b4ff-5ef6db3a8f81)

**Comment by board707** [comment]
Hi
See CONNECT_ZIGZAG option in the wiki
https://github.com/board707/DMD_STM32/wiki/Connections---Monochrome#connecting-more-than-one-panel

I hope it should works on RGB panels :)

**Comment by impuls-op** [comment]
Thanks for the quick response! The best support!

**Comment by board707** [comment]
Did you tested it?

**Comment by impuls-op** [comment]
Yes. added to config 
dmd.setConnectScheme(CONNECT_ZIGZAG);

And connected like a second photo (short cable). All it's good!
