### ISSUE TITLE
Add a new panel 128x64 s32 DP3364 driver

### ISSUE THREAD

**Issue by funnymind** [board707/DMD_STM32#127]
## Panel photos
1.
![photo_2024-08-30_22-06-42](https://github.com/user-attachments/assets/fd9d9f3f-b477-4cc5-90ff-c7d777ae26ef)
2.
![photo_2024-08-30_22-06-54](https://github.com/user-attachments/assets/1a144866-7c59-4886-9eac-0c965da1a866)
3.
![photo_2024-08-30_22-06-59](https://github.com/user-attachments/assets/87c88c1a-3d1c-4fc9-8e91-7cfb08a0e3dc)
4.
![photo_2024-08-30_22-07-03](https://github.com/user-attachments/assets/098d45cc-e644-4d84-a99f-0c6563f0dd11)

## Specifications

  - Library version: 1.1.5
  - Platform: STM32
  - MCU board: blackpill stm32f411ceu6
  - Connections: used pins A=PB6, B=PB5, C=PB4, D= PB3, nOE=PB0, SCLK=PB7, CLK=PA6, R0=PA0, G0=PA1, B0=PA2,
R1=PA3, G1=PA4, B1=PA5

**Comment by funnymind** [comment]
Hi @board707.
I have similar panels as were in this request #91. I saw that you were ready to do some tests on them, if you still don't mind then I'm ready. If it helps, I can drive them with huidu a3l player.

**Comment by board707** [comment]
Hi @funnymind 
Thank you for your kind offer of help.

The driver DP3364 is a S-PWM type. In order for it to work, it is necessary to do some reverse engineering to figure out it protocol and configuration settings.
Honesty speaking, it is very difficult to test unknown driver remotely. Fortunately, one library friend presents me a two panels with DP3364 driver :), so now I can work with them directly.
The issue is that I haven't much free time last days, so I can't say exactly when i'll be able to work on these panels.

**Comment by funnymind** [comment]
got it, thank you very much for the answer, if you need support from my side, I will be glad to help, though I have little experience in this kind of thing, as I said, they run on my player, I can try to record the output using the Saleae LOGIC analog, if that helps, or show the huidu hdset settings for this panels.

**Comment by kholia** [comment]
[DP3364S_Rev1.0_EN.pdf](https://github.com/user-attachments/files/20746086/DP3364S_Rev1.0_EN.pdf)

I found this datasheet online recently. Does this help OR are things still going to be incompatible?

Thank you!

**Comment by board707** [comment]
Hi @kholia 

Thank you very much. Even though I have this file, I still appreciate your willingness to help.
I am working on adding driver support to the library, but even with the datasheet it requires a lot of work, so I can't say when it will be finished.

**Comment by martodg** [comment]
Hi @board707 
I purchased a panel from Aliexpress with the DP3364S chip. If you ever update the library to add this driver, I will be very grateful.
https://www.aliexpress.com/item/1005006086019360.html
Thanks.
