### ISSUE TITLE
Problem with panel P5 64x32 with chip DP3265S

### ISSUE THREAD

**Issue by impuls-op** [board707/DMD_STM32#129]
I tested many panels 80x40, 64x32, 64x64 all is good. 
Today received a new panel GKGD P5 RGB 64x32 chip DP3265S
When i turn on panel (connect 4pin to 5v & IN hub75 to pi 2040) i can't see any LED with light. All leds in panel is off. 

![IMG_2138](https://github.com/user-attachments/assets/c952a35c-3d85-416f-bc6b-83942934e33e)

**Comment by board707** [comment]
Hi
According to internet info, the driver DP3265 is a S-PWM type and currently not supported by the library. Sorry.
