### ISSUE TITLE
Flex panels support

### ISSUE THREAD

**Issue by DoomHammer** [board707/DMD_STM32#130]
## Panel photos

![PXL_20240922_161434436 MP](https://github.com/user-attachments/assets/a2cc5e89-4eda-4cef-b444-a21ff2bf0d6a)
![PXL_20240922_161448536](https://github.com/user-attachments/assets/3770b271-44cb-48cb-bd44-69e32ec1bd2b)
![PXL_20240922_161504676 MP](https://github.com/user-attachments/assets/caa3b63e-2264-4ef1-9cf3-03fc04a6c930)

## Specifications

  - Library version: 1.01
  - Platform: Pi Pico
  - MCU board: Pi Pico
  - Connections: used pins

I have some flexible panels. Some of them are 64x32, some are 128x64. Whatever I do I cannot get them to display anything. Any clue what can I do to make them work?

**Comment by board707** [comment]
Hi

As I mentioned previously, the chip DP3265 is a S-PWM type driver. This driver is not supported in the current version of the library.

**Comment by DoomHammer** [comment]
What's necessary to add this support?

**Comment by board707** [comment]
The two things :) - i) I need a panel with the driver to be in my hands, ii) I need a lot of free time for testing. And the biggest problem with the latter.

**Comment by DoomHammer** [comment]
FIrst part is doable as I have a few of those. For the latter, I'm afraid I can't help. There's no rush with that, though.
