### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by krishnaTORQUE** [board707/DMD_STM32#132]
None of the examples are working.

```
Compilation error: 'mux_list' was not declared in this scope
```

**Comment by board707** [comment]
Hi @krishnaTORQUE 
I just tested a some examples and all of them were compiled fine.

Could you provide a more info about the problem? What the board do you use? What the version of the DMD_STM32 library?
Please show a full output for compiling errors.

**Comment by krishnaTORQUE** [comment]
This one: https://github.com/board707/DMD_STM32/blob/dev-V2/examples/STM32F4_RP2040/dmd_rgb/dmd_rgb.ino

I just copy & paste the entire code & tried to compile & got the error.

**Comment by board707** [comment]
What the board do you use?

**Comment by krishnaTORQUE** [comment]
STM23F411CEU

**Comment by board707** [comment]
Please show the compiler message in full

**Comment by krishnaTORQUE** [comment]
Github is preventing me to give you full debug log due to very large amounts of characters.

**Comment by board707** [comment]
You could pack it as ZIP and attach to the message

**Comment by krishnaTORQUE** [comment]
[debug-log.txt](https://github.com/user-attachments/files/17275811/debug-log.txt)

**Comment by board707** [comment]
You using a wrong STM32 Arduino package. The library is compatible with Roger Clark's [Arduino_STM32 package](https://github.com/rogerclarkmelbourne/Arduino_STM32) only.
Please see the library [Quick Start guide](https://github.com/board707/DMD_STM32/wiki/quick_start) for more details.
