### ISSUE TITLE
Add a new panel DP74HC138B + SM16208SC 32x16 8S

### ISSUE THREAD

**Issue by Danilo277** [board707/DMD_STM32#133]
## Panel photos
![0-02-05-69fc55f6d50be632b935b7dcc82a1c3ebb5bc3eae5c3e82018df7e6457b4c544_a72b5231ecfc9080](https://github.com/user-attachments/assets/a1b867d4-52b5-4e21-9a25-3e488995b98d)

## Sample videos
When uploaded "dmd_rgb_pattern_test" and only change "RGB32x16plainS4" to "RGB32x16plainS8".

https://github.com/user-attachments/assets/6a857c3a-11ff-4e9b-9577-05477063ccf2

## Specifications

I've tried a lot of combinations of settings but I'm literally nowhere near a solution :).

  - Library version: 1.1.5
  - Platform: STM32
  - MCU board: bluepill STM32F1
  - Connections: used pins - default

**Comment by board707** [comment]
Hi
In general, 32x16 panels with 8scans doesn't require any additional setting to work. Please show your code in full.

**Comment by Danilo277** [comment]
Thank you for the response!

The problem was a short circuit on the PCB. It was a manufacturing defect... everything works great now.
Best regards.
