### ISSUE TITLE
Как запустить P3-320x160-S13 

### ISSUE THREAD

**Issue by aidarishkulov** [board707/DMD_STM32#135]
#### Chips on rear side:  SM5166, DP5125

  - Library version: =1.1.6
  - Platform: RP2040 Zero
  - MCU board: RP2040
  - Connections: 
  - #define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 2
#define ENABLE_DUAL_BUFFER 0
#define DMD_PIN_A 6
#define DMD_PIN_B 7
#define DMD_PIN_C 8
#define DMD_PIN_D 9
#define DMD_PIN_E 10
#define DMD_PIN_OE 15
#define DMD_PIN_SCLK_LAT 12
#define DMD_PIN_CLK 11
#define DMD_PIN_R1 0
#define DMD_PIN_G1 1
#define DMD_PIN_B1 2
#define DMD_PIN_R2 3
#define DMD_PIN_G2 4
#define DMD_PIN_B2 5

Для улицы приобрел на [Р10.ru](http://out.arduino.ru/?redirect=http%3A%2F%2Fxn--10-tjc.ru%2F&baseU=https%3A%2F%2Fforum.arduino.ru%2Ft%2Fdmd-stm32-biblioteka-dmd-matricz-dlya-stm32-i-rp2040%2F8573%2F621) панели Р3-320х160-13S с чипами DP5125 и SM5166. Запускал с RGB104x52_S13_Craftish 4,104,52,13,59. Но, оказывается, там чипы не стандартные, у меня стандартные, тут читал об этом. Если изменить 59 и перебрать 1, 2, 3 должен заработать?

https://github.com/user-attachments/assets/295ef507-aa5f-4d52-8939-b0e782fbf34d

https://github.com/user-attachments/assets/14cf7289-b6a4-47fd-bffb-d146f9a37f93

**Comment by board707** [comment]
Здравствуйте
покажите код, с которым записано это видео

**Comment by aidarishkulov** [comment]
Здравствуйте!
Первый скетч:
#include "DMD_RGB.h"

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Output buffering - false
#define ENABLE_DUAL_BUFFER false

/* =================== *
*     STM32F4 pins     *
*  =================== */
#if (defined(__STM32F1__) || defined(__STM32F4__))
// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = {PA6, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

/* =================== *
*     RP2040 pins     *
*  =================== */
#elif (defined(ARDUINO_ARCH_RP2040))
// ==== DMD_RGB pins ====
// mux pins - A, B, C... mux pins must be consecutive in ascending order
#define DMD_PIN_A 6
#define DMD_PIN_B 7
#define DMD_PIN_C 8
#define DMD_PIN_D 9
#define DMD_PIN_E 10
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE 15
#define DMD_PIN_SCLK 12

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.2
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be consecutive in ascending order
uint8_t custom_rgbpins[] = { 11, 0,1,2,3,4,5 }; // CLK, R0, G0, B0, R1, G1, B1
#endif

// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>

// For pattern testing use one of matrix below:
// RGB32x16plainS4         - 32x16 1/4 Binary mux
// RGB32x16plainS4_DIRECT  - 32x16 1/4 Direct mux
// RGB32x16plainS2         - 32x16 1/2 Binary mux
// RGB32x16plainS2_DIRECT  - 32x16 1/2 Direct mux

//DMD_RGB <RGB32x16plainS4, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
DMD_RGB <RGB104x52_S13_Craftish, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

uint16_t bg = 0;  // background - black
uint16_t fg = 0;  // foreground

void setup(void)
{
    dmd.init();
    fg = dmd.Color888(0, 0, 255);
    dmd.setBrightness(50);
}

void loop(void) {
    // fill the matrix with points row by row
    for (int i = 0; i < dmd.height(); i++) {
        for (int j = 0; j < dmd.width(); j++) {
            dmd.drawPixel(j,i, fg);
            delay(30);
        }
    }
    // clear the screen
    dmd.fillScreen(bg);
}

**Comment by aidarishkulov** [comment]
Второй скетч:
`#include "DMD_RGB.h"

 // Fonts includes
#include "st_fonts/UkrRusArial14.h"
#pragma GCC diagnostic ignored "-Wnarrowing"
#pragma GCC diagnostic ignored "-Woverflow"
#include "gfx_fonts/GlametrixLight12pt7b.h"
#include "gfx_fonts/GlametrixBold12pt7b.h"
#pragma GCC diagnostic warning "-Wnarrowing"
#pragma GCC diagnostic warning "-Woverflow" 

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Enable of output buffering
// if true, changes only outputs to matrix after
// swapBuffers(true) command
// If dual buffer not enabled, all output draw at matrix directly
// and swapBuffers(true) cimmand do nothing
#define ENABLE_DUAL_BUFFER false
/* =================== *
*     STM32F4 pins     *
*  =================== */
#if (defined(__STM32F1__) || defined(__STM32F4__))
// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// контакт OE должен быть одним из PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Контакты для каналов R0, G0, B0, R1, G1, B1 и для часов.
// По умолчанию библиотека использует порядок цветов RGB.
// Если вам нужно это изменить — измените порядок контактов R0, G0, B0, R1, G1, B1.
// Все эти контакты также должны быть выбраны из одного порта!
uint8_t custom_rgbpins[] = {PA6, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

/* =================== *
*     RP2040 pins     *
*  =================== */
#elif (defined(ARDUINO_ARCH_RP2040))
// ==== DMD_RGB pins ====
// mux pins - A, B, C... mux pins must be consecutive in ascending order
#define DMD_PIN_A 6
#define DMD_PIN_B 7
#define DMD_PIN_C 8
#define DMD_PIN_D 9
#define DMD_PIN_E 10
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE 15
#define DMD_PIN_SCLK 12

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.2
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be consecutive in ascending order
uint8_t custom_rgbpins[] = { 11, 0,1,2,3,4,5 }; // CLK, R0, G0, B0, R1, G1, B1
#endif
// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>
// We use 64x32 matrix with 16 scans and 4bit color:
DMD_RGB <RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
// other options are:
// <RGB32x16plainS8> -  32x16 matrix with 8scans
// <RGB80x40plainS20> - 80x40 matrix with 20scans
// <RGB64x64plainS32> - 64x64 matrix with 32scans
// Color depth - <COLOR_4BITS_Packed>(STM32 only), <COLOR_4BITS> or <COLOR_1BITS> 


// --- Define fonts ----
// DMD.h old style font
DMD_Standard_Font UkrRusArial_F(UkrRusArial_14);
// GFX font with sepatate parts for Latin and Cyrillic chars
DMD_GFX_Font GlametrixL((uint8_t*)&GlametrixLight12pt7b, (uint8_t*)&GlametrixLight12pt8b_rus, 0x80, 13);


/*--------------------------------------------------------------------------------------
  UTF8 char recoding

--------------------------------------------------------------------------------------*/
int utf8_rus(char* dest, const unsigned char* src) {

    uint16_t i, j;
    for (i = 0, j = 0; src[i]; i++) {
        if ((src[i] == 0xD0) && src[i + 1]) { dest[j++] = src[++i] - 0x10; }
        else if ((src[i] == 0xD1) && src[i + 1]) { dest[j++] = src[++i] + 0x30; }
        else dest[j++] = src[i];
    }
    dest[j] = '\0';
    return j;
}

/*--------------------------------------------------------------------------------------
  setup
  Called by the Arduino architecture before the main loop begins
--------------------------------------------------------------------------------------*/

void setup(void)
{

    // initialize DMD objects
	dmd.init(); 

    // in case if your panels has a color orders other than RGB:
    //dmd.setColorOrder(DMD_Color_order :: BRG);
    
}


/*--------------------------------------------------------------------------------------
  loop
  Arduino architecture main loop
--------------------------------------------------------------------------------------*/

void loop(void)
{

    // create foreground colors
    uint16_t col[] = {
        dmd.Color888(255,0, 0), // red
        dmd.Color888(0, 255, 0), // green
        dmd.Color888(0, 0, 255)  // blue

    };
    uint16_t bg = 0;  // background - black
    int col_cnt = 3;   // color count

    // text
    char s[] = "Привет Ардуино!";
    // transcode message to UTF for use with GFX fonts
    char k[30];
    
    utf8_rus(k, (const unsigned char*)s);
    char* m = s;
    // select standard font
    dmd.selectFont(&UkrRusArial_F);
    
    // set text foreground and background colors
    dmd.setTextColor(col[0], bg);

    // shift steps in pixels for running text (positive - shift right, negative - left)
    int8_t step[] = { 1,-1,-2,2 };
    // running text shift interval
    uint32_t interval = 50;
    
    uint32_t prev_step = millis();
    uint8_t col_ptr = 0;
    uint8_t i = 0, b = 0;
    uint8_t test = 255;
    uint8_t test_cnt = 4;
    dmd.setBrightness(200);

    // Cycle for tests:
    // -- running texts moving at x and y axis with single and double speed
    // -- vertical scrolling message
    while (1) {
        if ((millis() - prev_step) > interval) {
            prev_step = millis();  // moved to the start of the loop to prevent "scroll not smooth" issue
            if (test >= test_cnt) {
                test = 0;
                // draw message
                dmd.drawMarqueeX(m, -1 * (dmd.stringWidth(m)), 0);
                
                dmd.swapBuffers(true);
                
            }
            switch (test) {
                // moving text at x axis
            case 0:
                if (dmd.stepMarquee(step[i], 0) & 1) { // if text is reached screen bounds

                    dmd.clearScreen(true);
                    // set next text color
                    col_ptr++;
                    if (col_ptr >= col_cnt) col_ptr = 0;
                    dmd.setTextColor(col[col_ptr], bg);
                    // set new text speed
                    i++;
                    // if all moving finished
                    if (i > 3) {
                        // go to next stage
                        i = 0;
                        test++;
                        dmd.drawMarqueeX(m, 0, (dmd.height() > 16)? 8 : 0);
                    }
                    else {
                        if (step[i] < 0) dmd.drawMarqueeX(m, dmd.width() - 1, 0);
                        else dmd.drawMarqueeX(m, -1 * dmd.stringWidth(m), 0);
                    }
                }
               
                // output mem buffer to matrix
                dmd.swapBuffers(true);
                break;
            case 1:
                b++;
                dmd.setBrightness(b);
                if (b > 250) {
                    test++;
                    b = 80;
                    i = 0;
                    dmd.setBrightness(b);
                    dmd.drawMarqueeX(m, 0, 0);
                }
                dmd.swapBuffers(true);
                break;
                // moving text at y axis
            case 2:
                if (dmd.stepMarquee(0, step[i]) & 1) {  // if text is reached screen bounds

                    // clear the screen
                    dmd.clearScreen(true);
                    // select new moving speed
                    i++;
                    // if all moving finished
                    if (i > 3) {
                        // go to next stage
                        test++;
                        // select GFX font for vertical scroll
                        dmd.selectFont(&GlametrixL);
                        dmd.drawMarquee(k, strlen(k), dmd.width() - 1,
                           (dmd.height() > 16)? 8 : 0, 1);

                    }
                    else {
                        if (step[i] < 0) dmd.drawMarqueeX(m, 0, dmd.height());
                        else dmd.drawMarqueeX(m, 0, 0);
                    }
                }
                // output mem buffer to matrix
                dmd.swapBuffers(true);
                break;

                // vertical scrolling    
            case 3:

                dmd.stepMarquee(-1, 0, 1);
                dmd.swapBuffers(true);
                break;

            }

         
        }
    }
}
`

**Comment by aidarishkulov** [comment]
Второй скетч:

#include "DMD_RGB.h"
 // Fonts includes
#include "st_fonts/UkrRusArial14.h"
#pragma GCC diagnostic ignored "-Wnarrowing"
#pragma GCC diagnostic ignored "-Woverflow"
#include "gfx_fonts/GlametrixLight12pt7b.h"
#include "gfx_fonts/GlametrixBold12pt7b.h"
#pragma GCC diagnostic warning "-Wnarrowing"
#pragma GCC diagnostic warning "-Woverflow" 

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Enable of output buffering
// if true, changes only outputs to matrix after
// swapBuffers(true) command
// If dual buffer not enabled, all output draw at matrix directly
// and swapBuffers(true) cimmand do nothing
#define ENABLE_DUAL_BUFFER false
#if (defined(__STM32F1__) || defined(__STM32F4__))
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// контакт OE должен быть одним из PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Контакты для каналов R0, G0, B0, R1, G1, B1 и для часов.
// По умолчанию библиотека использует порядок цветов RGB.
// Если вам нужно это изменить — измените порядок контактов R0, G0, B0, R1, G1, B1.
// Все эти контакты также должны быть выбраны из одного порта!
uint8_t custom_rgbpins[] = {PA6, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

#elif (defined(ARDUINO_ARCH_RP2040))
// mux pins - A, B, C... mux pins must be consecutive in ascending order
#define DMD_PIN_A 6
#define DMD_PIN_B 7
#define DMD_PIN_C 8
#define DMD_PIN_D 9
#define DMD_PIN_E 10
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE 15
#define DMD_PIN_SCLK 12

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.2
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be consecutive in ascending order
uint8_t custom_rgbpins[] = { 11, 0,1,2,3,4,5 }; // CLK, R0, G0, B0, R1, G1, B1
#endif
// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>
// We use 64x32 matrix with 16 scans and 4bit color:
DMD_RGB <RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
// other options are:
// <RGB32x16plainS8> -  32x16 matrix with 8scans
// <RGB80x40plainS20> - 80x40 matrix with 20scans
// <RGB64x64plainS32> - 64x64 matrix with 32scans
// Color depth - <COLOR_4BITS_Packed>(STM32 only), <COLOR_4BITS> or <COLOR_1BITS> 


// --- Define fonts ----
// DMD.h old style font
DMD_Standard_Font UkrRusArial_F(UkrRusArial_14);
// GFX font with sepatate parts for Latin and Cyrillic chars
DMD_GFX_Font GlametrixL((uint8_t*)&GlametrixLight12pt7b, (uint8_t*)&GlametrixLight12pt8b_rus, 0x80, 13);
int utf8_rus(char* dest, const unsigned char* src) {

    uint16_t i, j;
    for (i = 0, j = 0; src[i]; i++) {
        if ((src[i] == 0xD0) && src[i + 1]) { dest[j++] = src[++i] - 0x10; }
        else if ((src[i] == 0xD1) && src[i + 1]) { dest[j++] = src[++i] + 0x30; }
        else dest[j++] = src[i];
    }
    dest[j] = '\0';
    return j;
}

void setup(void)
{

    // initialize DMD objects
	dmd.init(); 

    // in case if your panels has a color orders other than RGB:
    //dmd.setColorOrder(DMD_Color_order :: BRG);
    
}

void loop(void)
{

    // create foreground colors
    uint16_t col[] = {
        dmd.Color888(255,0, 0), // red
        dmd.Color888(0, 255, 0), // green
        dmd.Color888(0, 0, 255)  // blue

    };
    uint16_t bg = 0;  // background - black
    int col_cnt = 3;   // color count

    // text
    char s[] = "Привет Ардуино!";
    // transcode message to UTF for use with GFX fonts
    char k[30];
    
    utf8_rus(k, (const unsigned char*)s);
    char* m = s;
    // select standard font
    dmd.selectFont(&UkrRusArial_F);
    
    // set text foreground and background colors
    dmd.setTextColor(col[0], bg);

    // shift steps in pixels for running text (positive - shift right, negative - left)
    int8_t step[] = { 1,-1,-2,2 };
    // running text shift interval
    uint32_t interval = 50;
    
    uint32_t prev_step = millis();
    uint8_t col_ptr = 0;
    uint8_t i = 0, b = 0;
    uint8_t test = 255;
    uint8_t test_cnt = 4;
    dmd.setBrightness(200);

    // Cycle for tests:
    // -- running texts moving at x and y axis with single and double speed
    // -- vertical scrolling message
    while (1) {
        if ((millis() - prev_step) > interval) {
            prev_step = millis();  // moved to the start of the loop to prevent "scroll not smooth" issue
            if (test >= test_cnt) {
                test = 0;
                // draw message
                dmd.drawMarqueeX(m, -1 * (dmd.stringWidth(m)), 0);
                
                dmd.swapBuffers(true);
                
            }
            switch (test) {
                // moving text at x axis
            case 0:
                if (dmd.stepMarquee(step[i], 0) & 1) { // if text is reached screen bounds

                    dmd.clearScreen(true);
                    // set next text color
                    col_ptr++;
                    if (col_ptr >= col_cnt) col_ptr = 0;
                    dmd.setTextColor(col[col_ptr], bg);
                    // set new text speed
                    i++;
                    // if all moving finished
                    if (i > 3) {
                        // go to next stage
                        i = 0;
                        test++;
                        dmd.drawMarqueeX(m, 0, (dmd.height() > 16)? 8 : 0);
                    }
                    else {
                        if (step[i] < 0) dmd.drawMarqueeX(m, dmd.width() - 1, 0);
                        else dmd.drawMarqueeX(m, -1 * dmd.stringWidth(m), 0);
                    }
                }
               
                // output mem buffer to matrix
                dmd.swapBuffers(true);
                break;
            case 1:
                b++;
                dmd.setBrightness(b);
                if (b > 250) {
                    test++;
                    b = 80;
                    i = 0;
                    dmd.setBrightness(b);
                    dmd.drawMarqueeX(m, 0, 0);
                }
                dmd.swapBuffers(true);
                break;
                // moving text at y axis
            case 2:
                if (dmd.stepMarquee(0, step[i]) & 1) {  // if text is reached screen bounds

                    // clear the screen
                    dmd.clearScreen(true);
                    // select new moving speed
                    i++;
                    // if all moving finished
                    if (i > 3) {
                        // go to next stage
                        test++;
                        // select GFX font for vertical scroll
                        dmd.selectFont(&GlametrixL);
                        dmd.drawMarquee(k, strlen(k), dmd.width() - 1,
                           (dmd.height() > 16)? 8 : 0, 1);

                    }
                    else {
                        if (step[i] < 0) dmd.drawMarqueeX(m, 0, dmd.height());
                        else dmd.drawMarqueeX(m, 0, 0);
                    }
                }
                // output mem buffer to matrix
                dmd.swapBuffers(true);
                break;

                // vertical scrolling    
            case 3:

                dmd.stepMarquee(-1, 0, 1);
                dmd.swapBuffers(true);
                break;

            }

         
        }
    }
}
Вставляется как то непонятно код

**Comment by board707** [comment]
Добрый день
Похоже что ваша матрица должна быть совместима с паттерном RGB104x52_S13_Craftish . Проблема в том, что этот паттерно только для плат STM32.  В коде для РП2040 используется другой принцип работы с матрицами и паттерн с ним не совместим. 
Я попробую адаптировать паттерн для РП2040, когда появится свободное время. К сожалению, у меня сейчас очень много работы.

**Comment by aidarishkulov** [comment]
Спасибо за ответ! Попробую с STM32F4.

**Comment by aidarishkulov** [comment]
ЛПолучил STMF103 и STMF411. Попробовал запустить этот код:
`/*--------------------------------------------------------------------------------------
 Demo for RGB panels

 DMD_STM32a example code for STM32F103xxx board

 Pattern test for 32x16 1/2 1/4 RGB panels
 ------------------------------------------------------------------------------------- */
 #include "DMD_RGB.h"

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Output buffering - false
#define ENABLE_DUAL_BUFFER false

// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = { PA15, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>

// For pattern testing use one of matrix below:
// RGB32x16plainS4         - 32x16 1/4 Binary mux
// RGB32x16plainS4_DIRECT  - 32x16 1/4 DIRECT mux
// RGB32x16plainS2_DIRECT  - 32x16 1/2 Binary mux

// Color depth - <COLOR_4BITS_Packed> or <COLOR_4BITS> 
// <COLOR_1BITS> mode is not recomended for bitmap

DMD_RGB <RGB104x52_S13_Craftish, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

uint16_t bg = 0;  // background - black
uint16_t fg = 0;  // foreground

void setup(void)
{
    // uncomment the line below if you using St-Link with STM32F103xx boards
    enableDebugPorts();
    
    dmd.init();
    fg = dmd.Color888(0, 0, 255);
    dmd.setBrightness(5);
}





void loop(void) {
    // fill the matrix with points row by row
    for (int i = 0; i < dmd.height(); i++) {
        for (int j = 0; j < dmd.width(); j++) {
            dmd.drawPixel(j,i, fg);
            delay(8);
        }
    }
    // clear the screen
    dmd.fillScreen(bg);
}`

**Comment by aidarishkulov** [comment]
STM32F103 

https://github.com/user-attachments/assets/11248294-8090-411b-af6d-a48707498860


STM32F411
Код во втором моем сообщении 
Видео 
https://github.com/user-attachments/assets/8f4387a9-3532-4f6c-be4a-aeb56561963a

**Comment by board707** [comment]
Hi
Thanks for the videos.
Your code is too fast to view something. Please increase the delay inside a `for` loops in the `loop()` function. You use a `delay(8)` now, change it to delay(30) or even delay(50). 
There is no need to record the process of completely filling the panel, 1-2 minutes is enough .

**Comment by aidarishkulov** [comment]
Снял.

https://github.com/user-attachments/assets/238f84f7-6642-4f5d-85a5-d3573734abe3

**Comment by board707** [comment]
Что-то тут не так. Вы точно не забыли увеличить задержку?

**Comment by aidarishkulov** [comment]
https://github.com/user-attachments/assets/b676b2b0-7aed-491d-bf6f-e3b998767da8

Поставил 100

**Comment by board707** [comment]
Нет, оно как-то совсем неправильно работает.
Уточните, это та самая панель, про которую Вы писали в начале?

> Dimensions (in pixels) : 104x52
> Scan factor: 1/13
> Chips on rear side: SM5166, DP5125

**Comment by aidarishkulov** [comment]
Да, эта панель.

**Comment by aidarishkulov** [comment]
Добавил в скетч после библиотеки
#define RGB104x52_S13_Craftish	 4,104,52,13,3

Uploading VID-20241111-WA0012.mp4…

**Comment by aidarishkulov** [comment]
Добавил в скетч после библиотеки
#define RGB104x52_S13_Craftish	 4,104,52,13,3

https://github.com/user-attachments/assets/94aafce2-20ad-4a72-8cde-25e7eb9e7c78

**Comment by aidarishkulov** [comment]
Если поменять в конце 3 на 2 так получается 
#define RGB104x52_S13_Craftish 4,104,52,13,2
https://github.com/user-attachments/assets/4a86b96e-1bb4-487d-923a-622cc3dba236

**Comment by board707** [comment]
Отлично!
Это значительно лучше! Сегодня уже поздно, завтра посмотрю внимательно.

**Comment by board707** [comment]
Попробуйте описать паттерн так
#define RGB104x52_S13_Craftish 4,104,52,13,112,8,PATTERN_LNS

**Comment by aidarishkulov** [comment]
> Попробуйте описать паттерн так #define RGB104x52_S13_Craftish 4,104,52,13,112,8,PATTERN_LNS

https://github.com/user-attachments/assets/00c48d2d-d26d-4514-9d4a-853752b90427

**Comment by aidarishkulov** [comment]
#define RGB104x52_S13_Craftish 4,104,52,13,102,4,PATTERN_UPS

https://github.com/user-attachments/assets/5c3f9b0b-19fe-4df3-ad16-818f7d0bf196

**Comment by board707** [comment]
Не надо редактировать строчки. которые я Вам пишу.
Это строка неправильная:

#define RGB104x52_S13_Craftish 4,104,52,13,102,4,PATTERN_UPS

Перед пераметром  PATTERN_UPS должна стоять цифра 8, а не 4.

Пожалуйста, выложите видео для паттерна
#define RGB104x52_S13_Craftish 4,104,52,13,112,8,PATTERN_LNS

не меняя в нем ничего.

**Comment by aidarishkulov** [comment]
Видео выше относится Вашей строке, другое видео с моей строкой удалил

**Comment by board707** [comment]
Ясно. спасибо.
Похоже не работает.
Попробуйте заменить в этой строке цифру 112 на 111, 101 и 102. Но если заполнение будет опять по 4 точки, то можете видео не записывать - значит шаблон не подходит.
Наверно я удаленно не смогу решить эту задачу.

**Comment by aidarishkulov** [comment]
> Ясно. спасибо. Похоже не работает. Попробуйте заменить в этой строке цифру 112 на 111, 101 и 102. Но если заполнение будет опять по 4 точки, то можете видео не записывать - значит шаблон не подходит. Наверно я удаленно не смогу решить эту задачу.
Проверил всё по 4 выводится.
Нельзя панель Вам отправить для теста? Вы в каком городе?

**Comment by board707** [comment]
Я в Москве

**Comment by aidarishkulov** [comment]
Можете скинуть адрес с куда отправить панель? proekt759@gmail.com

**Comment by aidarishkulov** [comment]
Спасибо автору Дмитрию за адаптирование вышеуказанных панелей  библиотеку, все работает хорошо.
Скоро панель появится в библиотеке.

**Comment by aidarishkulov** [comment]
Добрый день! Не планируете адаптировать библиотеку в плату STM32 от Espressif ?
Кларка ядро не поддерживается уже. В проекте может давать ошибку
>Message ID:  <board707/DMD_STM32/issues/135/2468509341 @ github . com> 
 
 
--
Айдар Ишкулов
Отправлено из Почты  Mail

**Comment by board707** [comment]
> Не планируете адаптировать библиотеку в плату STM32 от Espressif ? Кларка ядро не поддерживается уже.

В принципе когда-то стояло в планах, но сейчас отодвинул на дальнюю перспективу. спрос на СТМ32 маленький, в основном все новые проекты делаются на ЕСП32 и РП2040.
А в ядро Кларка я сам иногда дописываю то, что требуется :)
