### ISSUE TITLE
RP2040 PICO: setBrightness() doesn't work

### ISSUE THREAD

**Issue by xuniuer** [board707/DMD_STM32#139]
Hi @board707 ,

I test the function `setBrightness()` on RP2040 PICO board, it seems the function doesn't work. 
That is, the brightness is always same whaterver to setBrightness(0) or to setBrightness(255).

I try to find only for STM32 case `this->brightness` is used. For RP2040, it's forgotten.

I don't ensure if the above is an issue or not.

Thanks.

**Comment by board707** [comment]
Hi
Which panel are you experiencing this issue with? Not all drivers support brightness control.

**Comment by xuniuer** [comment]
I use P4 outdoor，80x40，10S，FM6124.

Thanks.



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/14/2024 17:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [board707/DMD_STM32] RP2040 PICO: setBrightness() doesn't work (Issue #139) |

Hi
Which panel are you experiencing this issue with? Not all drivers support brightness control.

**Comment by board707** [comment]
Could you show the code that you used for test?

**Comment by xuniuer** [comment]
Sorry, I cannot do it now.

Tomorrow morning at Beijing time, I will upload my test code.

Thanks.



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/14/2024 18:01 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [board707/DMD_STM32] RP2040 PICO: setBrightness() doesn't work (Issue #139) |

Could you show the code that you used for test?

**Comment by xuniuer** [comment]
Hi @board707 

The following is my test code, please check. 

The result is that the panel brightness is same.
 
``` c++
#include "DMD_RGB.h"

// Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 2

#define ENABLE_DUAL_BUFFER true
/* =================== *
 *     STM32F4 pins     *
 *  =================== */
#if (defined(__STM32F1__) || defined(__STM32F4__))
// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = {DMD_PIN_A, DMD_PIN_B, DMD_PIN_C, DMD_PIN_D, DMD_PIN_E};

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = {PA6, PA0, PA1, PA2, PA3, PA4, PA5}; // CLK, R0, G0, B0, R1, G1, B1

/* =================== *
 *     RP2040 pins     *
 *  =================== */
#elif (defined(ARDUINO_ARCH_RP2040))
// ==== DMD_RGB pins ====
// mux pins - A, B, C... mux pins must be consecutive in ascending order
#define DMD_PIN_A 6
#define DMD_PIN_B 7
#define DMD_PIN_C 8
#define DMD_PIN_D 9
#define DMD_PIN_E 10
// put all mux pins at list
uint8_t mux_list[] = {DMD_PIN_A, DMD_PIN_B, DMD_PIN_C, DMD_PIN_D, DMD_PIN_E};

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE 15
#define DMD_PIN_SCLK 12

uint8_t custom_rgbpins[] = {11, 0, 1, 2, 3, 4, 5}; // CLK, R0, G0, B0, R1, G1, B1
#endif

#define RGB80x40_s10_p4_6124_7262 4,80,40,10,102,1,PATTERN_LPS
typedef DMD_RGB<RGB80x40_s10_p4_6124_7262, COLOR_4BITS> RGB80x40_s10_p4_6124_7262_4bits;
RGB80x40_s10_p4_6124_7262_4bits dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

uint8_t brightness = 10;
uint16_t bgcolor = 0,
         fgcolor = 0;

void setup() {
    Serial.begin(115200);

    dmd.init();

    // across = 1, down = 2
    dmd.setConnectScheme(CONNECT_ZIGZAG);

    fgcolor = dmd.Color888(0, 0, 255);

    // set brightness firstly
    dmd.setBrightness(brightness);

    delay(8000); // to see output by serial monitor
    Serial.printf("Screen width = %d, height = %d\n", dmd.width(), dmd.height());
}

void loop() {
    // set brightness
    Serial.printf("Current brightness (0 ~ 255) : %3d\n", brightness);
    dmd.setBrightness(brightness);

    dmd.clearScreen(true);

    // here I fill the whole screen with (0, 0, 255)
    for(int i = 0; i < dmd.width(); i++) {
        for(int j = 0; j < dmd.height(); j++) {
            dmd.drawPixel(i, j, fgcolor);
        }
    }

    dmd.swapBuffers(true);

    // wait, try to tell brightness difference
    delay(1000);
    if (brightness > 128) brightness = 1; 
    else brightness += 5;
}
```

**Comment by board707** [comment]
Hi
I tested your code on two different panels (one with simple pattern and another with complex one, like yours).
The code works fine for me.

Keep in mind that brightness changes logarithmically, so changes at the beginning of the scale are more noticeable. In your code, for example, from brightness 30 to 128 the changes are almost imperceptible, while from 1 to 20 they are very visible.

To make the changes easier to notice, I suggest changing the brightness parameter also according to the logarithmic law:

```
if (brightness > 128) brightness = 1; 
    else brightness += 1 +  brightness/10 ;
```

**Comment by xuniuer** [comment]
Thanks for your efforts and suggestion.
I will have a try in the coming Monday.

BTW, I use platformio to build my project in which the DMD lib version 1.1.5 is used. And, your test is also based on the version, right?



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/16/2024 18:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [board707/DMD_STM32] RP2040 PICO: setBrightness() doesn't work (Issue #139) |

Hi
I tested your code on two different panels (one with simple pattern and another with complex one, like yours).
The code works fine for me.

Keep in mind that brightness changes logarithmically, so changes at the beginning of the scale are more noticeable. In your code, for example, from brightness 30 to 128 the changes are almost imperceptible, while from 1 to 20 they are very visible.

To make the changes easier to notice, I suggest changing the brightness parameter also according to the logarithmic law:

if (brightness > 128) brightness = 1; 
    else brightness += 1 +  brightness/10 ;

**Comment by xuniuer** [comment]
Hi @board707 ,

Now I update the library to current version - dev-V2.
And I try to use the logarithmic law to set brightness but no luck. I don't know why it cannot work for my case. Maybe the problem is about my panel.

Now I try to use color value to reflect the brightness change. Brightness value is 0 ~ 100 on behalf of brightness percentage. Then to use R,G,B to multiple the percentage to get a new R,G,B.  The result is not accurate but the brightness changes indeed. 

Thanks.

**Comment by board707** [comment]
Please explain in more detail what happens when the brightness changes? For example, if the brightness changes not gradually, as in your code, but immediately from brightness 1 to brightness 100? 
if the brightness does not change, which value is it closer to - 1 or 100?

> Maybe the problem is about my panel.

Your panel should not affect the operation of this algorithm, because it does not depend on the type of panel driver.

Did you test the brightness control with the same panel on STM32 based board?

**Comment by xuniuer** [comment]
> Did you test the brightness control with the same panel on STM32 based board?

Not yet. I will have a try some day.

---

I just to define a new function to change color values by brightness, like this:

```C++

typedef struct {
  uint8_t r, g, b;
} RGB;

uint16_t color_by_brightness(const RGB color, uint8_t brightness) {
    int r = (int)(1. * color.r * brightness / 100);
    int g = (int)(1. * color.g * brightness / 100);
    int b = (int)(1. * color.b * brightness / 100);

    return dmd.Color888(
        static_cast<uint8_t>(r), 
        static_cast<uint8_t>(g),
        static_cast<uint8_t>(b)
    );
}
```
I think the `brightness`(range: 0 ~ 100) is the percentage of color value. 
```
   100% -> 255
   50% -> 127 
   ...
```
The final color are not accurate but the difference, for me, could be ignored.

**Comment by board707** [comment]
Hi
Couldn't you figure out anything about the brightness issues?
Maybe try another rp2040 board, they glitch quite often...

**Comment by xuniuer** [comment]
You reminder me. I am using a  compatible board, it’s cheaper than official rp2040 pico.

I will order a new official pico to run test again.

So you can close the issue. If the brightness issue occurs on new official pico I could open the issue again.

Thanks.



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/20/2024 20:32 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [board707/DMD_STM32] RP2040 PICO: setBrightness() doesn't work (Issue #139) |

Hi
Couldn't you figure out anything about the brightness issues?
Maybe try another rp2040 board, they glitch quite often...

**Comment by xuniuer** [comment]
Hi @board707 

I have confirmed the above `issue` (setBrightness() does'nt work) is false. It works!

Reviewing my wiring, it seems that wiring with many dupont lines is not good approach. 
So, I make a simple PCB to fix the wiring. The picture is a part of that PCB.

![image](https://github.com/user-attachments/assets/b0907574-bede-45c1-b140-3be16b0190c1)

After testing, the problem disappears, that is, `setBrightness()` works.  

Thanks.

**Comment by board707** [comment]
Thank you for your feedback.
