### ISSUE TITLE
How can I do it?

### ISSUE THREAD

**Issue by digi55** [board707/DMD_STM32#141]
Hi, @board707 
How can I draw circles, triangles, arcs, etc. with your library? 
I want to make something like a car speedometer.
I want to show the value between 0-1000 with a needle moving on a semicircle.

**Comment by board707** [comment]
Since the library has inherited from Adafruit_GFX, that able you to use any drawing methods from parent library:
```
void drawLine()
void drawRect()
void drawCircle()
void fillCircle()
void drawTriangle()
void fillTriangle()
void drawRoundRect()
void fillRoundRect()
void drawBitmap()
void drawGrayscaleBitmap()
void drawRGBBitmap()
```

See the Adafruit_GFX documentation for details.

**Comment by digi55** [comment]
Thankyou @board707
