### ISSUE TITLE
P10 Monochrome support for Rpi pico 

### ISSUE THREAD

**Issue by maxmurugan** [board707/DMD_STM32#15]
I tested with P10RGB and P4RGB working well for using the clock same library will support P10 red module?

Please give the P10 red module support and also explain different scan method

please give me a P10 red module with Pico library.

**Comment by board707** [comment]
Hi, @maxmurugan 
Monochrome P10 panel support is planned in the next release.
It’s hard for me to give a date, as I don’t have much free time right now. 
Hopefully by the end of 2022

**Comment by board707** [comment]
Monochrome P10 panel support  for RP2040 boards added in v0.9.2
See the [example](https://github.com/board707/DMD_STM32/blob/dev-V2/examples/STM32F4_RP2040/dmd_monochrome/dmd_monochrome.ino)
