### ISSUE TITLE
DMD_PARA errors monochrome

### ISSUE THREAD

**Issue by BimoSora2** [board707/DMD_STM32#25]
DMD_RARA errors monochrome

![Screenshot pada 2023-01-28 09-42-55](https://user-images.githubusercontent.com/118399939/215238112-1c18e15b-4285-46d3-8607-b89f5745e73b.png)

![Screenshot pada 2023-01-28 09-43-07](https://user-images.githubusercontent.com/118399939/215238141-4b0bb567-245e-4fbd-bfc5-fa961e0d8f9f.png)

**Comment by board707** [comment]
Only Roger Clarks's repo https://github.com/rogerclarkmelbourne/Arduino_STM32 is supported for STM32 based boards
