### ISSUE TITLE
DMD+W5500

### ISSUE THREAD

**Issue by OkSingra** [board707/DMD_STM32#27]
Russian:
Могу ли я использовать данную библиотеку с модулем W5500? Есть ли прототип печатной платы для Pi Pico? Со своей стороны имею доступ ко многим панелям разных производителей, хочу протестировать на всех. Особенно интересны панели P2.5 128х64 с контактом D1между G1 и G2 (фото выложу позже) и 64х32 P5 (обе уличные). И еще нужно ли преобразовывать логику в 5V для всех панелей? подойдут ли 74HCT245?

Can I use this library with the W5500 module? Is there a prototype PCB for Pi Pico? For my part, I have access to many panels from different manufacturers, I want to test at all. Especially interesting are the panels P2.5 128x64 with contact D1 between G1 and G2 (I will post photos later) and 64x32 P5 (both street). And is it also necessary to convert the logic to 5V for all panels? Will 74HCT245 work?

**Comment by board707** [comment]
Hi, @OkSingra 

> Can I use this library with the W5500 module?

I have no ideas :) , I did not test it with W5500.

> For my part, I have access to many panels from different manufacturers, I want to test at all. Especially interesting are the panels P2.5 128x64 with contact D1 between G1 and G2 (I will post photos later) and 64x32 P5 (both street).

I doubt that your first panel will work with library, or at least it will require some modification of the code. About the last panel, 64x32 P5 , I can say nothing without the specification.

> is it also necessary to convert the logic to 5V for all panels? Will 74HCT245 work?

Some panels has logic buffers like 74HCT245 on board already. These panels do not need the logic conversion. The others can work unstable with 3.3v logic.

**Comment by wsandor** [comment]
Hi, @OkSingra

I use it with Ethernet_generic library with a W5500 module without problems.

**Comment by OkSingra** [comment]
Is it fixed somehow? The same error on all versions of arduino. Platformio also throws this error. I did not find a clear fix.

fatal error: pico/stdio.h: No such file or directory
 #include "pico/stdio.h"

**Comment by board707** [comment]
Please show complete error message. What code do you try to compile?

**Comment by OkSingra** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/111899241/217919216-db273019-8dbb-44e5-8d3e-a1c55807482a.png)

**Comment by board707** [comment]
The "arduino-mbed" framework, that you use - is incompatible with the library. 
Please read the section [Compatible IDE and libraries](https://github.com/board707/DMD_STM32#compatible-ide-and-libraries) of the library README.
For RP2040 boards only Earle Philhower arduino core is supported.

**Comment by OkSingra** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/111899241/217923858-6cbd075b-ad9f-4ca0-818a-ed1f0774a29f.png)
Thanks a lot. Works great!

**Comment by OkSingra** [comment]
![Снимок экрана от 2023-02-10 15-18-30](https://user-images.githubusercontent.com/111899241/218090962-d96ceb23-a660-4bef-8602-03c236751718.png)
<strike>On Windows 11 it was not possible to start the correct work with the platformio.</strike> On Linux Mint, everything worked correctly. On Windows  works.

**Comment by OkSingra** [comment]
![IMG_20230210_182502](https://user-images.githubusercontent.com/111899241/218129657-3f8fcbe2-ee99-412f-a690-8ad930e3d606.jpg)

**Comment by OkSingra** [comment]
Can I change the pins at my discretion?

**Comment by board707** [comment]
About the STM32 connections see the wiki: [RGB panel connections](https://github.com/board707/DMD_STM32/wiki/Connections---RGB)
For RP2040 you can select any pins under the following conditions: pins A B C D E must have consecutive numbers, the same applies to R0 G0 B0 R1 G1 B1

**Comment by OkSingra** [comment]
https://youtu.be/FO7wHBfsk_8

Does not work. Now I'm trying to get another panel.

https://youtu.be/ELxcs0bZFr8 This another panel

![photo_2023-02-16_11-43-38](https://user-images.githubusercontent.com/111899241/219313468-e8966c23-f470-4428-b7c7-728656afc15e.jpg)
![photo_2023-02-16_11-43-43](https://user-images.githubusercontent.com/111899241/219313510-b02199f3-88a9-4163-8190-2d6182d750d9.jpg)

Please contact me via telegram @Hiderstv

**Comment by board707** [comment]
> Please contact me via telegram @Hiderstv

sorry, I do not have a telegram

**Comment by OkSingra** [comment]
> sorry, I do not have a telegram

Mail?

**Comment by board707** [comment]
please write me dd@jwee.ru
