### ISSUE TITLE
24bit color depth no supported?

### ISSUE THREAD

**Issue by Thermaltake** [board707/DMD_STM32#30]
P10, HUB75, 1/4 scan, outdoor
STM32F103C8 and STM32F401CCU6

```
DMD_RGB <RGB32x16_S4_BIN, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, 2, 1, false);

 for (int i = 0; i < 255; i++)
  {
      fg = dmd.Color888(i,0,0);
      dmd.fillScreen(fg);
      delay(5);
  }
```

In this form, the display misses the brightness of the LEDs, because of this there is no smoothness.
The COLOR_8BITS constant do not exist.
In file DMD_RGB.h need parameters in template DMD_RGB_BASE2?

Also in the current version, the led screen does not burn at full brightness. Based on power consumption.

**Comment by board707** [comment]
The library supports Adafruit565 16bits colors only. 24bits color support is a problem because the lack of the 24bits colors in the AdafruitGFX library, used as base class for DMD_STM32 code.
