### ISSUE TITLE
p4 module 32x64 pixel

### ISSUE THREAD

**Issue by maxmurugan** [board707/DMD_STM32#40]
char s[] = "welcome to board707  abcdefghijklmnopqrstuvwxyz";

dmd.drawString(0,a10,strlen(a10),col[4]);

fill first line remaining char go to next line automatically

how to program ?

please help sir

**Comment by board707** [comment]
Your code is not clear for me
```
char s[] = "welcome to board707 abcdefghijklmnopqrstuvwxyz";
dmd.drawString(0,a10,strlen(a10),col[4]);
```

The string in the first line has name `s`, but in second line you try to display `a10` and `col`.
What do you try to achieve?

**Comment by board707** [comment]
Closed due to the lack of a response from the author.
Fill free to reopen it if needed.
