### ISSUE TITLE
won't display big string

### ISSUE THREAD

**Issue by damir27777** [board707/DMD_STM32#5]
Hi, I have problem to display big string from serial input. Stm32 recived string 350 charachters but only displays 170. Help?

**Comment by board707** [comment]
The maximum string length of static and moving text should be 256 chars because of the datatype of length parameter = byte.

**Comment by board707** [comment]
I just tested the code with a string of 250 characters - static and moving text was shown completely. It looks like errors in your code that received data from Serial input. To check, try to output a long string from a variable.
