### ISSUE TITLE
Weird scan pattern

### ISSUE THREAD

**Issue by DoomHammer** [board707/DMD_STM32#54]
Hi @board707 !

Here's some more details about the cursed panel with weird pattern.

It's 2 mux pins, 2 scan lines, and what you see uses `#define DISPLAY_TYPE 2,32,16,2,1`

![PXL_20231024_125207952](https://github.com/board707/DMD_STM32/assets/695373/7b143290-62e3-4e09-8bd7-0b45ee5c1f57)

https://github.com/board707/DMD_STM32/assets/695373/eea6d7c9-18c0-40e3-afa8-76f75ee6c169

**Comment by board707** [comment]
> #define DISPLAY_TYPE 2,32,16,2,1

try this variants:

 2,32,16,2,2
 2,32,16,2,3
 1,32,16,2,2
 1,32,16,2,2

**Comment by DoomHammer** [comment]
Do you want recording from there or just a plain "works/doesn't"?

**Comment by board707** [comment]
If any of them will run more than 2 pixels horizontally in a serie...

**Comment by DoomHammer** [comment]
With 1 mux line, the pixels get two levels of brightness (or something like that) after some time

## 2,32,16,2,2

https://github.com/board707/DMD_STM32/assets/695373/05dec579-4d87-429d-ae69-8b36a9d25f30

## 2,32,16,2,3

https://github.com/board707/DMD_STM32/assets/695373/44517e7e-11bd-49f6-9d69-de5eec0ba835

## 1,32,16,2,2 (this was mentioned twice by you, on purpose?)

https://github.com/board707/DMD_STM32/assets/695373/60e57f76-1d44-4014-9072-0a2a8eb73376

**Comment by board707** [comment]
Disconnect the "B" line from the STM and connect B pin on the HUB to GND permanently. Than run the pattern 1,32,16,2,2 again. Will it run up to full panel width? The more long video could be useful

**Comment by DoomHammer** [comment]
Again I'm using a PCB here, so no way to change connections. Will try when I set up another board.

**Comment by board707** [comment]
Connecting B to the GND is not the main thing; when selecting one pin mux , the B pin should already have a low level.
The main thing is: do the pixels go to the end of the panel?

**Comment by board707** [comment]
Hi, did you resolved the problem?

**Comment by DoomHammer** [comment]
Not yet, didn't have time to give it my proper attention since the last time :(

**Comment by board707** [comment]
Ok, 
If you will need my help, write.

Merry Christmas!
