### ISSUE TITLE
Novelty ways of joining the panels

### ISSUE THREAD

**Issue by DoomHammer** [board707/DMD_STM32#55]
I have 5 32x16 P10 panels that I'd like to put to some use. They are some rare parts so I assume it'd be hard to find anything compatible with them, therefore I'd like to use all 5 of them at once.

This gives me some possibilities regarding connections and resolutions:

Simple 5x1 for 160x16 display

Classy 2x2 for 64x32 display

The second could be potentially more sueful but then one panels is left without job.

An alternative popped to my mind abou usin 5x1 but sideways to give a nice 80x32 display with ribbons coming in a zigzag shape from behind.

The thing is: how best to approach this from the code perspective as I assume the library is not ready for such crazy ways of behavior?

**Comment by board707** [comment]
> An alternative popped to my mind abou usin 5x1 but sideways to give a nice 80x32 display with ribbons coming in a zigzag shape from behind.

You can easily put 5 panels one above another, giving the 1x5 configuration, and than rotate the screen to 90 deg, so it will be 80x32 display. However, despite the fact that the library has a rotate() function, most of the methods are tied to the horizontal position of the panels and most likely there will be problems when used.

But it's could be an interesting experience :)
