### ISSUE TITLE
Add a new panel 128x64 32s  FM6363C, DP245D

### ISSUE THREAD

**Issue by sevket-karayilan** [board707/DMD_STM32#65]
## Panel photos
![00003db0-4b4d-4bb2-906c-2fda0a64ffe0](https://github.com/board707/DMD_STM32/assets/103222176/637ac25d-8c30-475c-9705-9d94dfa17c0e)
![abe33c12-3be5-4412-a6cf-22757211dc22](https://github.com/board707/DMD_STM32/assets/103222176/d0643852-2e83-4455-a2d1-806ef7ba803f)
![4a8f6910-f63e-45bf-9c85-5306374cc5c9](https://github.com/board707/DMD_STM32/assets/103222176/30b75ebe-26de-4c65-968a-6e938e4baf11)
![5ebd464c-03f4-48e0-b3c8-17bf7fae90e3](https://github.com/board707/DMD_STM32/assets/103222176/fd7000bc-c8d5-44e6-ada8-d9df76067cd7)
![ddd9332f-70f7-489e-9370-443fff2da4bc](https://github.com/board707/DMD_STM32/assets/103222176/30a127d4-4f1e-42d5-8cf3-4753cd95ef38)

## Specifications

  - Library version: 1.01
  - Platform: STM32
  - MCU board: bluepil STM32F103
  - Connections: use pattern test default pins

**Comment by board707** [comment]
Hi
Your panel has a scan factor 32  =  half of height, therefore it is not require any specific operation to add. The version 1.1.0 of the library already should support of the your matrix.

To control the panel with FM6363 driver you need to add

`#include "DMD_RGB_FM6353.h"`

header to the beginning of the code and initialise the dmd object as `DMD_RGB_FM6363` class.
