### ISSUE TITLE
Not able to complite using stm32duino

### ISSUE THREAD

**Issue by ravigyanvihar** [board707/DMD_STM32#71]
Sir I tried your library after trying adafuit protomatter . It working way better . I run on raspberry pi pico . But when I compile using lastest stmduino images I am not able to compile the code . Please help with that

**Comment by board707** [comment]
The library is not compatible with stmduino packages. It requires Roger Clarks's Arduino_STM32 repo. Please read "[Compatible IDE and libraries](https://github.com/board707/DMD_STM32/tree/dev-V2#compatible-ide-and-libraries)" section of library Readme file.
