### ISSUE TITLE
About the "Parrallel connection" method, how to connect the dot matrix screen to the MCU

### ISSUE THREAD

**Issue by ShiPC123** [board707/DMD_STM32#76]
IN the link https://github.com/board707/DMD_STM32/wiki/Connections---Monochrome#connecting-more-than-one-panel
I found that the matrix screen can be Parrallel connection, but in the example file, I found that the code only declares the following pins.
<img width="696" alt="image" src="https://github.com/board707/DMD_STM32/assets/132763025/2168fecd-a9c6-469d-bdf3-3f67ef2c6283">

<img width="562" alt="image" src="https://github.com/board707/DMD_STM32/assets/132763025/7a657e8c-f4c1-4356-ba6d-5143cd385e61">

But part of the actual HUB75 pin （such as R1 G1 B1 R2 G2 B2）is not used, how should I match the IO of the MCU with the lattice screen? Can you give me a wiring diagram?
In addition, I found definitions of SCLK and CLK in the code. Is SCLK corresponding to LAT in HUB75E PORT and CLK corresponding to HUB75 PORT CLK?
In addition the code uint8_t pins[] = {PA5, PA7, PA6}; // In CLK, row1, row 2

Pin PA7 which Note row1 ,what pin should I connect to the first dot screen in the first row

**Comment by board707** [comment]
Hi
The link that you mentioned named "Connections - Monochrome"
The parallel connection mode is applicated only to monochrome HUB12 panels and not to RGB HUB75 ones.

**Comment by ShiPC123** [comment]
Thank you very much In addition, I found definitions of SCLK and CLK in the code. Is SCLK corresponding to LAT in HUB75E PORT and CLK corresponding to CLK IN HUB75 PORT ?

**Comment by ShiPC123** [comment]
Whether the RGB dot matrix screen supports ZIGZAG connection mode

**Comment by board707** [comment]
I think so, it should work

**Comment by ShiPC123** [comment]
In addition, I found definitions of SCLK and CLK in the code. Is SCLK corresponding to LAT in HUB75E PORT and CLK corresponding to CLK IN HUB75 PORT ?

**Comment by board707** [comment]
Yes, SCLK in HUB12 corresponds to LAT signal in HUB75.
 The CLK signal has the same name and meanings both in HUB12 and HUB75 interfaces.
