### ISSUE TITLE
Add a new panel 80x40 s10 TC7262D, FM6124D

### ISSUE THREAD

**Issue by digi55** [board707/DMD_STM32#80]
#### Scan factor: 
![20240222_103810](https://github.com/board707/DMD_STM32/assets/160831820/9b0bdd6a-2522-4b59-8275-bd8b6ffa3cc3)
![20240222_103902](https://github.com/board707/DMD_STM32/assets/160831820/a525acc9-7a9a-480e-82a6-84c2ed6e4d50)
![20240222_104000](https://github.com/board707/DMD_STM32/assets/160831820/7f641a28-b09d-4651-81c5-c0f0273fc4b6)
![20240222_104032](https://github.com/board707/DMD_STM32/assets/160831820/1944d0de-e0e1-40c4-83ac-0a8b705a0b91)

## Specifications

  - Library version: 1.1.2
  - Platform: STM32
  - MCU board: bluepil STM32F103C8T6
  - Connections:  A=PB6, B=PB5, C=PB4, D= PB3, D=PB8     nOE=PB0,   SCLK=PB7   CLK=PA6,  R0=PA0,  G0=PA1, B0=PA2, 
 R1=PA3,  G1=PA4,  B1=PA5

**Comment by board707** [comment]
Hi!
What is a scan factor of the panel? It seems to me that it is 1/10 ?

Do you test it with `RGB80x40_S10_LNikon` pattern?

**Comment by digi55** [comment]
Hello
sorry I don't know the scan factor of this panel
yes i tested (RGB80x40_S10_LNikon)
I am sending a video
I used , dmd rgb turk in example

https://github.com/board707/DMD_STM32/assets/160831820/336e327b-2576-4630-b037-4115f808cc64

**Comment by board707** [comment]
Sorry, but your video is empty.
Can you upload it on Youtube and send the link?

**Comment by digi55** [comment]
https://github.com/board707/DMD_STM32/assets/160831820/096c6da2-2942-464b-8e6d-17bfa1dabc0f

dmd_rgb_test_pattern with RGB80x40_S10_LNikon
It constantly writes on these 4 lines.

**Comment by board707** [comment]
How do you upload the code to your STM board? Via St-Link or via USB bootloader?

Also, in your connections:
>  A=PB6, B=PB5, C=PB4, D= PB3, D=PB8 

Is the second "D" pin just a typo and should be read as "E=PB8" ?

**Comment by digi55** [comment]
Thank you for your helps.
I am using ST-Link programmer
Sorry for mistake , I used E=PB8

I did not change the pin structure, I use the configuration, which you gave in the example

**Comment by board707** [comment]
Please add the line `enableDebugPorts();` at the first line of `setup()` function

**Comment by digi55** [comment]
enableDebugPorts(); After this command

Everything is OK.
Thank you so much, For your helps.

**Comment by board707** [comment]
Thank you for your feedback!
