### ISSUE TITLE
Set Custom Font

### ISSUE THREAD

**Issue by tahafathi2013** [board707/DMD_STM32#81]
How set custom font to show text??
for example : 

SystemFont5x7
Arial_black_16
Arial14

how set in code??

**Comment by board707** [comment]
Using Arial14 font:

1. Include font file to the sketch:
` #include "st_fonts/Arial14.h"`

2. Create Font object:
`DMD_Standard_Font Arial_F(Arial_14); `

3. Select font to use with text:
`dmd.selectFont(&Arial_F); `

4. Print the text with selected font:
` dmd.drawStringX(0, 15, text, color); `


See the examples for more info.
