### ISSUE TITLE
Add a new panel 128x64 s32 SN16380SF

### ISSUE THREAD

**Issue by digi55** [board707/DMD_STM32#82]
## Specifications

  - Library version: 1.1.2
  - Platform: STM32
  - MCU board: bluepil STM32F103C8T6
  - Connections: used pins   A=PB6, B=PB5, C=PB4, D= PB3, E=PB8   nOE=PB0,   SCLK=PB7   CLK=PA6,    R0=PA0, G0=PA1, B0=PA2,
R1=PA3, G1=PA4, B1=PA5
![20240223_091108](https://github.com/board707/DMD_STM32/assets/160831820/43816531-6439-4b38-8f90-7abcb073b066)
![20240223_091251](https://github.com/board707/DMD_STM32/assets/160831820/408496ba-8b0e-477c-93b4-04184be3fba3)
![20240223_130054](https://github.com/board707/DMD_STM32/assets/160831820/d7d53c86-77e4-4702-a17c-4d687582ebf9)

**Comment by board707** [comment]
Unfortunately, your panel is based on a S-PWM type driver  SM16380 that is not supported by the library.

**Comment by digi55** [comment]
Thank you for information!

24 Şub 2024 Cmt 13:05 tarihinde board707 ***@***.***> şunu
yazdı:
