### ISSUE TITLE
Add a new panel please - P10 32x16 s2 MB5124

### ISSUE THREAD

**Issue by boba7** [board707/DMD_STM32#83]
## Panel photos
![20240223_090555](https://github.com/board707/DMD_STM32/assets/161023102/cac5df0f-cebd-4249-9c4a-89fb216b66ba)

## Sample videos
After i played around with it it looks like 32x16 1/2 DIRECT, colors work great, but pixels are all over the place. Managed to do this rgb_pattern_test with 2,32,16,2,1
https://drive.google.com/file/d/11GrxtMxfKp6CHncX78fGxA4tgWcdIvDC/view?usp=drivesdk
## Specifications

  - Library version: 1.1.2
  - Platform: STM32
  - MCU board: STM32F103C
  - Connections: used pins: A = PB6, B = PB5, C = NC, D = NC, E = NC,  nOE = PB0, SCLK = PA7, CLK = PA6, R0 = PA0, G0 = PA1, B0 = PA2, R1 = PA3, G1 = PA4, B1 = PA5

**Comment by board707** [comment]
Hi
Please show the video for rgb_pattern_test with 2,32,16,2,2

**Comment by boba7** [comment]
Here it is with 2,32,16,2,2
https://drive.google.com/file/d/11x0oFkoV6i7-9aCGgfVNz-fBaXZDX8PG/view?usp=drivesdk

**Comment by board707** [comment]
Thank you, I'll take a time to figure out this.

**Comment by board707** [comment]
Hi
Insert the code below in your sketch just after line
`#include "DMD_RGB.h"`


```
#define RGB32x16_s2_boba7 2,32,16,2,63

template<int COL_DEPTH>
class DMD_RGB<RGB32x16_s2_boba7, COL_DEPTH> : public DMD_RGB_BASE2<COL_DEPTH>
{
  public:
    DMD_RGB(uint8_t* mux_list, byte _pin_nOE, byte _pin_SCLK, uint8_t* pinlist,
            byte panelsWide, byte panelsHigh, bool d_buf = false) :
      DMD_RGB_BASE2<COL_DEPTH>(2, mux_list, _pin_nOE, _pin_SCLK, pinlist,
                               panelsWide, panelsHigh, d_buf, COL_DEPTH, 2, 32, 16)
    {
      this->fast_Hbyte = false;
      this->use_shift = false;
    }
    // Fast text shift is disabled for complex patterns, so we don't need the method
    void disableFastTextShift(bool shift) override {}

protected:
	uint16_t get_base_addr(int16_t &x, int16_t &y) override {
		this->transform_XY(x, y);
		uint8_t pol_y = y % this->pol_displ;
		x += (y / this->DMD_PIXELS_DOWN) * this->WIDTH;
              
		static const uint8_t px_base = 8;
                static const uint8_t D_tbl[4] = { 3, 2, 1, 0 };
                static const uint8_t C_tbl[4] = { 1, 0, 1, 0 };

		uint16_t base_addr = (pol_y % this->nRows) * this->x_len + (x / px_base) * this->multiplex * px_base ;
                uint8_t Oktet_m = pol_y / this->nRows;
                base_addr += D_tbl[Oktet_m] * px_base;
                if ( C_tbl[Oktet_m] == 1) {
                 base_addr += (px_base -1) - x % px_base;
                }
               else
               {
                 base_addr += x % px_base;
               }
		return base_addr;

		}

};
```

**Comment by boba7** [comment]
It's working! Thank you!
![20240226_160330](https://github.com/board707/DMD_STM32/assets/161023102/dc7bfe70-9ae1-4144-9d6f-0a343b827452)

**Comment by board707** [comment]
Congratulations :)
Thanks for your feedback.

**Comment by board707** [comment]
Added your matrix to main library.
You can use it just as `RGB32x16_s2_boba7` pattern.

Thank you for trying the library.

**Comment by vandana-itspe** [comment]
hi @board707, I am using RGB32x16_s2_boba7 matrix and thanks for the library, I am facing a small issue, the right side of the board is flickering and the color is comparatively dim. Could you help me out with this?

**Comment by board707** [comment]
Hi
Could you show the video illustrated the issue?

**Comment by vandana-itspe** [comment]
> Hi Could you show the video illustrated the issue?

Hi, here is the video. 

https://github.com/board707/DMD_STM32/assets/151005627/bd4e5ab6-a8c2-4c40-bc87-d62863b2bd21

the dimming part is not clearly visible in the video, but I can see with the naked eye

**Comment by board707** [comment]
It looks like a broken panel. Do you have another one for test?

**Comment by vandana-itspe** [comment]
It is not broken, I have cascaded 2 (32x16) panels in parallel.

**Comment by board707** [comment]
Please describe your connections in more detail. The RGB panels can't connected in parallel, you should chain it one to another.

**Comment by vandana-itspe** [comment]
yes, I have connected in a daisy chain,  the output of one panel goes to input of next.

**Comment by board707** [comment]
Try to swap first and second panels.
Will the issue still on the same panel or moved to another?

**Comment by vandana-itspe** [comment]
As I swapped the panels, the issue has moved to above panel.

**Comment by board707** [comment]
If the issue does still on the same panel - it means that the problem is in the panel itself.

**Comment by vandana-itspe** [comment]
but the issue has shifted to another panel after I swap, before it was on the bottom panel and after swap it is on the above panel

**Comment by board707** [comment]
Please correct me if I wrong....
First the issue was on bottom panel, right?
Then you swapped the panels, and issue now is in the above panel, isn't it?
But when you swapped the panels, the bottom panel became the top - therefore the issue now in the same panel as before.
