### ISSUE TITLE
Scrolling text is not smooth

### ISSUE THREAD

**Issue by maxmurugan** [board707/DMD_STM32#86]
hi sir ,
 Panel description 
 Dimensions (in pixels) : 32x16
Scan factor: 1/4
Specifications
Library version: 1.01
Platform: Pico

I try to using below setting and video file

https://github.com/board707/DMD_STM32/assets/4962604/39b253d4-a635-401f-9029-22d3d5240235

DMD_RGB <RGB32x16plainS4, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

**Comment by maxmurugan** [comment]
sm16208s
138 decoder ic

**Comment by maxmurugan** [comment]
please check

**Comment by board707** [comment]
Sorry, I am on vacation now. I will return after 20 March

Try 
RGB32x16_S4_VitaliyDKZ
pattern

**Comment by maxmurugan** [comment]
ok

**Comment by board707** [comment]
Did you try the
RGB32x16_S4_VitaliyDKZ
 pattern?

**Comment by maxmurugan** [comment]
I try not working please check video

https://github.com/board707/DMD_STM32/assets/4962604/4308d869-3aa0-4b02-adbb-8a53eab32476


RGB32x16_S4_VitaliyDKZ

**Comment by maxmurugan** [comment]
tomorrow will check sir

**Comment by board707** [comment]
Please be patient, I will resolve this when return home after 20th March

**Comment by maxmurugan** [comment]
RGB32x16_S4_VitaliyDKZ  this setting working fine

I am using Scrolling text speed is 20 middle of the going slow when compared to the start of the text
please check video and code

if ((millis() - prev_step) > interval)
    {
       dmd.setTextColor(col[R1], bg);    // --red color
       if (dmd.stepMarquee(-1, 0) & 1) { // if text is reached screen bounds
        dmd.clearScreen(true);
        Refresh =0;
        dmd.drawMarquee(Final_Message, strlen(Final_Message) , dmd.width() - 5, (dmd.height() > 0) ? 0 : 0, 0);
      }
      dmd.swapBuffers(true);
      prev_step = millis();
    }


https://github.com/board707/DMD_STM32/assets/4962604/8c103844-b4c5-40fb-90d1-04edc369ab71

**Comment by maxmurugan** [comment]
When your free please check this code

**Comment by board707** [comment]
Ok

**Comment by tahafathi2013** [comment]
> RGB32x16_S4_VitaliyDKZ this setting working fine
> 
> I am using Scrolling text speed is 20 middle of the going slow when compared to the start of the text please check video and code
> 
> if ((millis() - prev_step) > interval) { dmd.setTextColor(col[R1], bg); // --red color if (dmd.stepMarquee(-1, 0) & 1) { // if text is reached screen bounds dmd.clearScreen(true); Refresh =0; dmd.drawMarquee(Final_Message, strlen(Final_Message) , dmd.width() - 5, (dmd.height() > 0) ? 0 : 0, 0); } dmd.swapBuffers(true); prev_step = millis(); }
> 
>  IMG_9825.MOV


HOW ITS WORKING??
WHAT IS PIN CONFIG?
WHAT IS PANEL CONFIGS?
I USE STM32 BLUEPIL BUT NOT WORKING ON RGB PANELS.64X32 16 S.

Please full code is working upload here.

**Comment by maxmurugan** [comment]
I am using Raspberry pi Pico

**Comment by board707** [comment]
> When your free please check this code

What is the problem?
As I understand, the pattern RGB32x16_S4_VitaliyDKZ is works with your panel?

**Comment by maxmurugan** [comment]
Scrolling text  is not smooth from start to end

**Comment by board707** [comment]
Yes, I noticed that too in some modes on my panels. It seems to me that when you have all the text on panels, the controller simply does not have time to update it between scans. 
Unfortunately, I don't have a solution to this problem right now. I can only advise reducing the text speed.

**Comment by board707** [comment]
Hi @maxmurugan 
Please test a workaround to the "text is not  smooth" problem.
Your main scrolling code is:
```
if ((millis() - prev_step) > interval)
{
dmd.setTextColor(col[R1], bg); // --red color
if (dmd.stepMarquee(-1, 0) & 1) { // if text is reached screen bounds
dmd.clearScreen(true);
Refresh =0;
dmd.drawMarquee(Final_Message, strlen(Final_Message) , dmd.width() - 5, (dmd.height() > 0) ? 0 : 0, 0);
}
dmd.swapBuffers(true);
prev_step = millis();
}
```
Look at the code - the millis mark is updated at the very end, after the text has been shifted. This means that our update interval is not exactly 20ms, but 20ms + the time the controller needs to redraw the marquee. This time depends greatly on the number of letters on the screen. At the beginning and at the end there are only a couple of letters on the panel and everything is redrawn quickly, but in the middle you need to display all the text and this takes a long time.
To eliminate unevenness, you need to move the time mark to the beginning of the cycle:
```
if ((millis() - prev_step) > interval)
{
prev_step = millis();
dmd.setTextColor(col[R1], bg); // --red color
if (dmd.stepMarquee(-1, 0) & 1) { // if text is reached screen bounds
dmd.clearScreen(true);
Refresh =0;
dmd.drawMarquee(Final_Message, strlen(Final_Message) , dmd.width() - 5, (dmd.height() > 0) ? 0 : 0, 0);
}
dmd.swapBuffers(true);

}
```

**Comment by maxmurugan** [comment]
sorry for delay i am trying today sir

**Comment by board707** [comment]
Did you trying the fix I suggested?

**Comment by maxmurugan** [comment]
sorry for delay

now get scrolling text smooth

**Comment by maxmurugan** [comment]
https://github.com/board707/DMD_STM32/assets/4962604/b79e2a5e-6d32-4aa7-8431-a24837e1c4e2

**Comment by maxmurugan** [comment]
Future Multiline scrolling possible?

**Comment by board707** [comment]
Thank you for your feedback.

> Multiline scrolling possible?

This can be done with current code. Please open a new issue for it.
