### ISSUE TITLE
RGB P5 MODULE PIN CONNECTION

### ISSUE THREAD

**Issue by tahafathi2013** [board707/DMD_STM32#87]
im use p5 rgb module.
But i have not pin E on my module.
Module have 
R1 - G1
B1 - GND
R2 - G2
B2 - GND
A - B
C - D
CLK - LAT
OE - GND

![IMG_20240305_144147](https://github.com/board707/DMD_STM32/assets/19773695/e9301a22-4b11-4713-9b10-4cbe62a0d497)

**Comment by tahafathi2013** [comment]
![IMG_20240305_163735](https://github.com/board707/DMD_STM32/assets/19773695/8bd82cf5-5fa3-4349-80fa-153b77cece30)

![IMG_20240305_163725](https://github.com/board707/DMD_STM32/assets/19773695/b7eb9e8b-09c9-49c7-996f-eb2540b63cc2)

![IMG_20240305_163717](https://github.com/board707/DMD_STM32/assets/19773695/7801523e-3262-4d91-acff-56f6560cbceb)

![IMG_20240305_163644](https://github.com/board707/DMD_STM32/assets/19773695/55dd474f-08ff-435b-96c4-2f108df0db1e)

**Comment by tahafathi2013** [comment]
https://github.com/board707/DMD_STM32/assets/19773695/c6e91bf9-3cfa-425d-8874-62212ecb3464

**Comment by board707** [comment]
Hi, 
you have a 16scan panel, it is not need a E pin.

If you have a problem with the library with your panel, please show your test code with all connections defined.

**Comment by tahafathi2013** [comment]
im use this code :

`/*--------------------------------------------------------------------------------------
 Demo for RGB panels

 DMD_STM32a example code for STM32F103xxx board

 Pattern test for 32x16 1/2 1/4 RGB panels
 ------------------------------------------------------------------------------------- */
 #include "DMD_RGB.h"

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Output buffering - false
#define ENABLE_DUAL_BUFFER false

// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = { PA15, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>

// For pattern testing use one of matrix below:
// RGB32x16plainS4         - 32x16 1/4 Binary mux
// RGB32x16plainS4_DIRECT  - 32x16 1/4 DIRECT mux
// RGB32x16plainS2_DIRECT  - 32x16 1/2 Binary mux
// example:
//   #define RGB80x40plainS20  5,80,40,20,0		// 5 mux pins(A B C D E), 80x40, scan 1/20, pattern 0
//
//             pattern_ID is unique number for pattern design
//			   pattern ID between 0 and 31 and after 255 are reserved for library use
//                       and from 32 to 127 - for user panels, added by author
//            for new panels added yourself use pattern_ID between 128 and 255
//
DMD_RGB <RGB64x32plainS16  , 4> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

uint16_t bg = 0;  // background - black
uint16_t fg = 0;  // foreground

void setup(void)
{
    dmd.init();
    fg = dmd.Color888(0, 0, 255);
    dmd.setBrightness(50);
}

void loop(void) {
    // fill the matrix with points row by row
    for (int i = 0; i < dmd.height(); i++) {
        for (int j = 0; j < dmd.width(); j++) {
            dmd.drawPixel(j,i, fg);
            delay(30);
        }
    }
    // clear the screen
    dmd.fillScreen(bg);
}
`

im connected led panel to stm32 pins:

#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8

and connected this pins : 

uint8_t custom_rgbpins[] = { PA15, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

my panel dont have sclk pin to connect PB7 but im connect this pin to PA15

**Comment by board707** [comment]
Don.t confuse the CLK and the SCLK pins.
The library SCLK pin is the same as LAT pin on the panel.
You should connect PA15 to CLK and PB7 to LAT.

**Comment by tahafathi2013** [comment]
pin connection :
P5 - STM32
R1 - A0
G1 - A1
B1 - A2

R2 - A3
G2 - A4
B2 - A5
-------------
A - B6
B - B5
C - B4
D - B3

CLK - A15
LAT - B7
OE - B0

MY CODE : 

/*--------------------------------------------------------------------------------------
 Demo for RGB panels

 DMD_STM32a example code for STM32F103xxx board

 Pattern test for 32x16 1/2 1/4 RGB panels
 ------------------------------------------------------------------------------------- */
 #include "DMD_RGB.h"

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Output buffering - false
#define ENABLE_DUAL_BUFFER false

// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = { PA15, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>

// For pattern testing use one of matrix below:
// RGB32x16plainS4         - 32x16 1/4 Binary mux
// RGB32x16plainS4_DIRECT  - 32x16 1/4 DIRECT mux
// RGB32x16plainS2_DIRECT  - 32x16 1/2 Binary mux

DMD_RGB <RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

uint16_t bg = 0;  // background - black
uint16_t fg = 0;  // foreground

void setup(void)
{
    dmd.init();
    fg = dmd.Color888(0, 0, 255);
    dmd.setBrightness(50);
}

void loop(void) {
    // fill the matrix with points row by row
    for (int i = 0; i < dmd.height(); i++) {
        for (int j = 0; j < dmd.width(); j++) {
            dmd.drawPixel(j,i, fg);
            delay(30);
        }
    }
    // clear the screen
    dmd.fillScreen(bg);
}


BUT NOT WORKIN . . . .



https://github.com/board707/DMD_STM32/assets/19773695/6589fc9d-25f0-476e-8e4b-c2d605282fae

**Comment by tahafathi2013** [comment]
how fix it???


https://github.com/board707/DMD_STM32/assets/19773695/1942a67b-1a56-4b0e-a513-076fde59806f

**Comment by board707** [comment]
Sorry, l am not home now.

**Comment by tahafathi2013** [comment]
Ok
No problem.
When you at home chek this problem and help me  to fix it.please

**Comment by board707** [comment]
Do you use a st-link to upload the code to the stm32?

**Comment by tahafathi2013** [comment]
No im using serial programmer

**Comment by tahafathi2013** [comment]
how fix it problem??

**Comment by tahafathi2013** [comment]
![IMG_20240307_021649](https://github.com/board707/DMD_STM32/assets/19773695/af8700ea-5246-44a7-a753-e8036234750d)

**Comment by tahafathi2013** [comment]
/*--------------------------------------------------------------------------------------
 Demo for RGB panels

 DMD_STM32a example code for STM32F103xxx board
 ------------------------------------------------------------------------------------- */
#include "DMD_RGB.h"

// Fonts includes
#include "st_fonts/UkrRusArial14.h"
#pragma GCC diagnostic ignored "-Wnarrowing"
#pragma GCC diagnostic ignored "-Woverflow"
#include "gfx_fonts/GlametrixLight12pt7b.h"
#include "gfx_fonts/GlametrixBold12pt7b.h"
#pragma GCC diagnostic warning "-Wnarrowing"
#pragma GCC diagnostic warning "-Woverflow"

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Enable of output buffering
// if true, changes only outputs to matrix after
// swapBuffers(true) command
// If dual buffer not enabled, all output draw at matrix directly
// and swapBuffers(true) cimmand do nothing
#define ENABLE_DUAL_BUFFER false
#define LED_PIN PC13


// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// CLK, R0, G0, B0, R1, G1, B1
#define DMD_PIN_R0 PA0
#define DMD_PIN_G0 PA1
#define DMD_PIN_B0 PA2
#define DMD_PIN_R1 PA3
#define DMD_PIN_G1 PA4
#define DMD_PIN_B1 PA5
#define DMD_CLK PA15




// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A, DMD_PIN_B, DMD_PIN_C, DMD_PIN_D };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PA7
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = { DMD_CLK, DMD_PIN_R1, DMD_PIN_G1, DMD_PIN_B1, DMD_PIN_R0, DMD_PIN_G0, DMD_PIN_B0 };  // CLK, R0, G0, B0, R1, G1, B1

// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>
// We use 64x32 matrix with 16 scans and 4bit color:
DMD_RGB<RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
// other options are:
// <RGB32x16plainS8> -  32x16 matrix with 8scans
// <RGB80x40plainS20> - 80x40 matrix with 20scans
// <RGB64x64plainS32> - 64x64 matrix with 32scans
// Color depth - <COLOR_4BITS_Packed>, <COLOR_4BITS> or <COLOR_1BITS>


// --- Define fonts ----
// DMD.h old style font
DMD_Standard_Font UkrRusArial_F(UkrRusArial_14);
/// GFX font with sepatate parts for Latin and Cyrillic chars
DMD_GFX_Font GlametrixL((uint8_t*)&GlametrixLight12pt7b, (uint8_t*)&GlametrixLight12pt8b_rus, 0x80, 13);


uint16_t bg = 0;  // background - black
uint16_t fg = 50;   // foreground

/*--------------------------------------------------------------------------------------
  setup
  Called by the Arduino architecture before the main loop begins
--------------------------------------------------------------------------------------*/


void setup(void) {
  // initialize DMD objects
  dmd.init();
  fg = dmd.Color888(0, 0, 255);
  dmd.setBrightness(200);
}


/*--------------------------------------------------------------------------------------
  loop
  Arduino architecture main loop
--------------------------------------------------------------------------------------*/

void loop(void) {

  // fill the matrix with points row by row
  for (int i = 0; i < dmd.height(); i++) {
    for (int j = 0; j < dmd.width(); j++) {
      dmd.drawPixel(j, i, fg);
      delay(30);
    }
  }
  // clear the screen
   dmd.fillScreen(bg);
 
}

**Comment by tahafathi2013** [comment]
I remove DMD_PIN_E

**Comment by tahafathi2013** [comment]
![IMG_20240306_214419](https://github.com/board707/DMD_STM32/assets/19773695/ece5581f-a391-49a5-a6c0-476e63a06fe3)

**Comment by board707** [comment]
Try to use pb8 to pin D and pb10 as pin C.
Also you have an incorrect order of RGB pins: pins R0G0B0 should be first and then R1 G1 B1

**Comment by tahafathi2013** [comment]
I try it but not working yet.
When my hand near wire of clk pin 

https://github.com/board707/DMD_STM32/assets/19773695/fb0f8e36-ec3b-4ae3-92df-6cf85afbe95a



![IMG_20240307_025954](https://github.com/board707/DMD_STM32/assets/19773695/daec2708-00bf-48d2-9daa-998bcbed4622)

**Comment by tahafathi2013** [comment]
/*--------------------------------------------------------------------------------------
 Demo for RGB panels

 DMD_STM32a example code for STM32F103xxx board
 ------------------------------------------------------------------------------------- */
#include "DMD_RGB.h"

// Fonts includes
#include "st_fonts/UkrRusArial14.h"
#pragma GCC diagnostic ignored "-Wnarrowing"
#pragma GCC diagnostic ignored "-Woverflow"
#include "gfx_fonts/GlametrixLight12pt7b.h"
#include "gfx_fonts/GlametrixBold12pt7b.h"
#pragma GCC diagnostic warning "-Wnarrowing"
#pragma GCC diagnostic warning "-Woverflow"

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Enable of output buffering
// if true, changes only outputs to matrix after
// swapBuffers(true) command
// If dual buffer not enabled, all output draw at matrix directly
// and swapBuffers(true) cimmand do nothing
#define ENABLE_DUAL_BUFFER false
#define LED_PIN PC13


// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB10
#define DMD_PIN_D PB8
// CLK, R0, G0, B0, R1, G1, B1
#define DMD_PIN_R0 PA0
#define DMD_PIN_G0 PA1
#define DMD_PIN_B0 PA2
#define DMD_PIN_R1 PA3
#define DMD_PIN_G1 PA4
#define DMD_PIN_B1 PA5
#define DMD_CLK PA15




// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A, DMD_PIN_B, DMD_PIN_C, DMD_PIN_D };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PA7
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = { DMD_CLK, DMD_PIN_R0, DMD_PIN_G0, DMD_PIN_B0, DMD_PIN_R1, DMD_PIN_G1, DMD_PIN_B1 };  // CLK, R0, G0, B0, R1, G1, B1

// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>
// We use 64x32 matrix with 16 scans and 4bit color:
DMD_RGB<RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
// other options are:
// <RGB32x16plainS8> -  32x16 matrix with 8scans
// <RGB80x40plainS20> - 80x40 matrix with 20scans
// <RGB64x64plainS32> - 64x64 matrix with 32scans
// Color depth - <COLOR_4BITS_Packed>, <COLOR_4BITS> or <COLOR_1BITS>


// --- Define fonts ----
// DMD.h old style font
DMD_Standard_Font UkrRusArial_F(UkrRusArial_14);
/// GFX font with sepatate parts for Latin and Cyrillic chars
DMD_GFX_Font GlametrixL((uint8_t*)&GlametrixLight12pt7b, (uint8_t*)&GlametrixLight12pt8b_rus, 0x80, 13);


uint16_t bg = 0;  // background - black
uint16_t fg = 50;   // foreground

/*--------------------------------------------------------------------------------------
  setup
  Called by the Arduino architecture before the main loop begins
--------------------------------------------------------------------------------------*/


void setup(void) {
  // initialize DMD objects
  dmd.init();
  fg = dmd.Color888(0, 255, 0);
  dmd.setBrightness(200);
}


/*--------------------------------------------------------------------------------------
  loop
  Arduino architecture main loop
--------------------------------------------------------------------------------------*/

void loop(void) {
 fg = dmd.Color888(0, 0, 255);
  // fill the matrix with points row by row
  for (int i = 0; i < dmd.height(); i++) {
    for (int j = 0; j < dmd.width(); j++) {
      dmd.drawPixel(j, i, fg);
      delay(30);
    }
  }
  // clear the screen
   dmd.fillScreen(bg);
   
   
   fg = dmd.Color888(0, 255, 0);
  // fill the matrix with points row by row
  for (int i = 0; i < dmd.height(); i++) {
    for (int j = 0; j < dmd.width(); j++) {
      dmd.drawPixel(j, i, fg);
      delay(30);
    }
  }
  // clear the screen
   dmd.fillScreen(bg);
   
   
   fg = dmd.Color888(255, 0, 0);
  // fill the matrix with points row by row
  for (int i = 0; i < dmd.height(); i++) {
    for (int j = 0; j < dmd.width(); j++) {
      dmd.drawPixel(j, i, fg);
      delay(30);
    }
  }
  // clear the screen
   dmd.fillScreen(bg);
 
}

**Comment by board707** [comment]
Sorry, I don't have any additional ideas.

**Comment by tahafathi2013** [comment]
DMD_RGB<RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
IN this line code need to change RGB64x32plainS16, COLOR_4BITS????

why when CLK pin touched by my finger turned on half?

**Comment by board707** [comment]
>why when CLK pin touched by my finger its working ?

The matrix code uses a high frequency pulses (dozen megahertz) and it is very sensitive to unreliable connections. Do not use separate wires, use dedicated 16pin connector.

**Comment by tahafathi2013** [comment]
Choose wich cpu spee?
Im use 16 pin connector or wires but dont work it.
My panel dont have pin  E but im remove pin E from code.
What is configure without pin E??
Please get me example without pin E to test screen

**Comment by board707** [comment]
Pin E is not used for matrices with 16 scans or lower, so this setting doesn't matter for your configuration.
Honestly, I don't see any problems with your pins setup. I don't have an idea why it not works.

**Comment by tahafathi2013** [comment]
ok
your examples why not working adafruit gfx 1.11 ??
what your panel models tested by your examples stm32 f103c8t6c???

**Comment by board707** [comment]
The library works with Adafruit Gfx v 1.7 , the link is in the Readme. But your question surprised me, if you would to use incorrect adafrit gfx version, the code doesn't compile.
The library tested with dozens of different panels. Your panel looks compatible, your code is correct , and your connections is right. It should work.
Sorry for inconvenience, but I don't know how to help you.

**Comment by tahafathi2013** [comment]
It may be because of uploading the code through serial? It means that it has not been transmitted through the correct serial?
Could it be because of the (https://github.com/rogerclarkmelbourne/Arduino_STM32)?

**Comment by tahafathi2013** [comment]
I change pin numbers to this but not working
this time use st link programmer .
but not working again.


/*--------------------------------------------------------------------------------------
 Demo for RGB panels

 DMD_STM32a example code for STM32F103xxx board

 Pattern test for 32x16 1/2 1/4 RGB panels
 ------------------------------------------------------------------------------------- */
 #include "DMD_RGB.h"

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Output buffering - false
#define ENABLE_DUAL_BUFFER false

// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB10
#define DMD_PIN_D PB8
//#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D  };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = { PA15, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>

// For pattern testing use one of matrix below:
// RGB32x16plainS4         - 32x16 1/4 Binary mux
// RGB32x16plainS4_DIRECT  - 32x16 1/4 DIRECT mux
// RGB32x16plainS2_DIRECT  - 32x16 1/2 Binary mux

DMD_RGB <RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

uint16_t bg = 0;  // background - black
uint16_t fg = 0;  // foreground

void setup(void)
{
    dmd.init();
    fg = dmd.Color888(0, 0, 255);
    dmd.setBrightness(50);
}

void loop(void) {
    // fill the matrix with points row by row
    for (int i = 0; i < dmd.height(); i++) {
        for (int j = 0; j < dmd.width(); j++) {
            dmd.drawPixel(j,i, fg);
            delay(30);
        }
    }
    // clear the screen
    dmd.fillScreen(bg);
}

**Comment by tahafathi2013** [comment]
![IMG_20240310_135930](https://github.com/board707/DMD_STM32/assets/19773695/351e4d9f-ced2-4c8f-83d3-8a47ea3a01b0)


When programmed with stlink

**Comment by tahafathi2013** [comment]
When press reset key moving leds.

https://github.com/board707/DMD_STM32/assets/19773695/bee7594e-a650-46df-a0c3-855354a1219b

**Comment by digi55** [comment]
/*--------------------------------------------------------------------------------------
 Demo for RGB panels

 DMD_STM32a example code for STM32F103xxx board

 Pattern test for 32x16 1/2 1/4 RGB panels
 ------------------------------------------------------------------------------------- */
 #include "DMD_RGB.h"

//Number of panels in x and y axis
#define DISPLAYS_ACROSS 1
#define DISPLAYS_DOWN 1

// Output buffering - false
#define ENABLE_DUAL_BUFFER false

// ==== DMD_RGB pins ====
// mux pins - A, B, C... all mux pins must be selected from same port!
#define DMD_PIN_A PB6
#define DMD_PIN_B PB5
#define DMD_PIN_C PB4
#define DMD_PIN_D PB3
#define DMD_PIN_E PB8
// put all mux pins at list
uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };

// pin OE must be one of PB0 PB1 PA6 PA7
#define DMD_PIN_nOE PB0
#define DMD_PIN_SCLK PB7

// Pins for R0, G0, B0, R1, G1, B1 channels and for clock.
// By default the library uses RGB color order.
// If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins.
// All this pins also must be selected from same port!
uint8_t custom_rgbpins[] = { PA6, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1

// Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>

// For pattern testing use one of matrix below:
// RGB32x16plainS4         - 32x16 1/4 Binary mux
// RGB32x16plainS4_DIRECT  - 32x16 1/4 DIRECT mux
// RGB32x16plainS2_DIRECT  - 32x16 1/2 Binary mux
// <RGB80x40plainS20> - 80x40 matrix with 20scans

DMD_RGB <RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
//DMD_RGB <RGB80x40plainS20, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
//DMD_RGB <RGB128x64plainS32, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);

uint16_t bg = 0;  // background - black
uint16_t fg = 0;  // foreground

void setup(void)
{
  enableDebugPorts();
  dmd.init();
  fg = dmd.Color888(0, 0, 255);
  dmd.setBrightness(50);
}

void loop(void) {
    // fill the matrix with points row by row
    for (int i = 0; i < dmd.height(); i++) {
        for (int j = 0; j < dmd.width(); j++) {
            dmd.drawPixel(j,i, fg);
            delay(30);
        }
    }
    // clear the screen
    dmd.fillScreen(bg);
}

**Comment by digi55** [comment]
Hi, Try this Code. Working without problem with me.

**Comment by digi55** [comment]
Thank you so much @board707

**Comment by tahafathi2013** [comment]
> /*-------------------------------------------------------------------------------------- Demo for RGB panels
> 
> DMD_STM32a example code for STM32F103xxx board
> 
> Pattern test for 32x16 1/2 1/4 RGB panels ------------------------------------------------------------------------------------- */ #include "DMD_RGB.h"
> 
> //Number of panels in x and y axis #define DISPLAYS_ACROSS 1 #define DISPLAYS_DOWN 1
> 
> // Output buffering - false #define ENABLE_DUAL_BUFFER false
> 
> // ==== DMD_RGB pins ==== // mux pins - A, B, C... all mux pins must be selected from same port! #define DMD_PIN_A PB6 #define DMD_PIN_B PB5 #define DMD_PIN_C PB4 #define DMD_PIN_D PB3 #define DMD_PIN_E PB8 // put all mux pins at list uint8_t mux_list[] = { DMD_PIN_A , DMD_PIN_B , DMD_PIN_C , DMD_PIN_D , DMD_PIN_E };
> 
> // pin OE must be one of PB0 PB1 PA6 PA7 #define DMD_PIN_nOE PB0 #define DMD_PIN_SCLK PB7
> 
> // Pins for R0, G0, B0, R1, G1, B1 channels and for clock. // By default the library uses RGB color order. // If you need to change this - reorder the R0, G0, B0, R1, G1, B1 pins. // All this pins also must be selected from same port! uint8_t custom_rgbpins[] = { PA6, PA0,PA1,PA2,PA3,PA4,PA5 }; // CLK, R0, G0, B0, R1, G1, B1
> 
> // Fire up the DMD object as dmd<MATRIX_TYPE, COLOR_DEPTH>
> 
> // For pattern testing use one of matrix below: // RGB32x16plainS4 - 32x16 1/4 Binary mux // RGB32x16plainS4_DIRECT - 32x16 1/4 DIRECT mux // RGB32x16plainS2_DIRECT - 32x16 1/2 Binary mux // - 80x40 matrix with 20scans
> 
> DMD_RGB <RGB64x32plainS16, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER); //DMD_RGB <RGB80x40plainS20, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER); //DMD_RGB <RGB128x64plainS32, COLOR_4BITS> dmd(mux_list, DMD_PIN_nOE, DMD_PIN_SCLK, custom_rgbpins, DISPLAYS_ACROSS, DISPLAYS_DOWN, ENABLE_DUAL_BUFFER);
> 
> uint16_t bg = 0; // background - black uint16_t fg = 0; // foreground
> 
> void setup(void) { enableDebugPorts(); dmd.init(); fg = dmd.Color888(0, 0, 255); dmd.setBrightness(50); }
> 
> void loop(void) { // fill the matrix with points row by row for (int i = 0; i < dmd.height(); i++) { for (int j = 0; j < dmd.width(); j++) { dmd.drawPixel(j,i, fg); delay(30); } } // clear the screen dmd.fillScreen(bg); }

what use board?? 
im using bluepill
it work on bluepill?

**Comment by digi55** [comment]
Yes, Iam using also P5 panel like yours and bluepill. 
Be careful about pin number

**Comment by tahafathi2013** [comment]
![IMG_20240310_152859](https://github.com/board707/DMD_STM32/assets/19773695/a4438d05-c5ab-4bff-ba7c-a3d21d4a70c1)

I using your code but not working .
Can you upload image from your wire connections an your panel details.
My panel not have E pin.

**Comment by digi55** [comment]
Picture won't help since I'm using a FLAT cable. Pin numbers are as seen in the sample code I sent.
PinE is not required on this panel.

**Comment by tahafathi2013** [comment]
i when use fg = dmd.Color888(255, 255, 255); not change the color.

**Comment by tahafathi2013** [comment]
> Picture won't help since I'm using a FLAT cable. Pin numbers are as seen in the sample code I sent. PinE is not required on this panel.

my wire connections same as sample code.but not working

**Comment by digi55** [comment]
This code fills the panel with blue dots.

**Comment by tahafathi2013** [comment]
I change the colors

 fg = dmd.Color888(255, 255, 255)
But not working.

**Comment by digi55** [comment]
send a picture of your connections

**Comment by digi55** [comment]
I will check for you

**Comment by tahafathi2013** [comment]
Are you install and configure stm boards from https://github.com/rogerclarkmelbourne/Arduino_STM32 ???
Change any thing on your board like resistors?

I burn bootloader by cub programmer. And upload the code by stlink.

**Comment by tahafathi2013** [comment]
![IMG_20240310_154859](https://github.com/board707/DMD_STM32/assets/19773695/6403230c-0ed1-4fe6-b566-c653d9b51124)

![IMG_20240310_154849](https://github.com/board707/DMD_STM32/assets/19773695/0f8cfca1-6541-4a57-8f30-fb826960ea4f)

**Comment by digi55** [comment]
in my code CLK PIN = PA6
you are usingPA15, please change it

**Comment by tahafathi2013** [comment]
I change it but not working yet.

![IMG_20240310_161523](https://github.com/board707/DMD_STM32/assets/19773695/43b27836-6933-4d86-8e95-7ffd4354068d)

**Comment by digi55** [comment]
Sorry ,I don't have any advice

**Comment by tahafathi2013** [comment]
> Sorry ,I don't have any advice

Is it possible that the micro or the micro flash memory is damaged?


![IMG_20240310_162435](https://github.com/board707/DMD_STM32/assets/19773695/6ae98bf0-9735-4f94-8dd9-89cdf28b5714)

This my config for bluepill

**Comment by tahafathi2013** [comment]
I have sometimes error when upload project

![IMG_20240310_162705](https://github.com/board707/DMD_STM32/assets/19773695/17ab9487-8c0e-4d0e-a8bb-18f440aaad0a)

**Comment by tahafathi2013** [comment]
Are you install and configure stm boards from https://github.com/rogerclarkmelbourne/Arduino_STM32 ???
Change any thing on your board like resistors?

**Comment by digi55** [comment]
yes,  I am using https://github.com/rogerclarkmelbourne/Arduino_STM32 
No, Nothing change

**Comment by tahafathi2013** [comment]
are you install maple driver? 
i just copy arduino_stm32 folder to my doucument/arduino/hardware .
and install sam cortext_m3 and use your code

**Comment by tahafathi2013** [comment]
what is stlink pin connections to stm32 bluepiil?
i need to disconnect stlink programmer after uploading code???
can you make a vide from pin connection and your programmer and your arduino board setting? please
