### ISSUE TITLE
Add a new panel 128x64 s32 DP3364 driver

### ISSUE THREAD

**Issue by digi55** [board707/DMD_STM32#91]
## Panel photos
![20240306_131151](https://github.com/board707/DMD_STM32/assets/160831820/c776376a-33cc-4697-9c63-cb504b64e3df)
![20240306_132307](https://github.com/board707/DMD_STM32/assets/160831820/9efe01af-75ec-47dc-9cad-3fda1043b1d9)
![20240306_132339](https://github.com/board707/DMD_STM32/assets/160831820/2bc8beb0-331d-4426-bfaa-c5bf59a39b9c)
![20240306_132421](https://github.com/board707/DMD_STM32/assets/160831820/f0fff37d-79d0-4a2f-a5e6-ca30a0594c7a)

## Specifications

  - Library version: 2.0
  - Platform: STM32
  - MCU board: bluepill STM32103C8T6
  - Connections: used pins  A=PB6, B=PB5, C=PB4, D= PB3, E=PB8 nOE=PB0, SCLK=PB7 CLK=PA6, R0=PA0, G0=PA1, B0=PA2,
R1=PA3, G1=PA4, B1=PA5

**Comment by board707** [comment]
Hi
Unfortunately, prognosis is negative: I didn't find anything about DP3364 driver, its closest analog, DP3264 is S-PWM type and incompatible with the library.

Try to test the panel with DMD_RGB_SHIFTREG_ABC class and pattern RGB128x64plainS32

**Comment by digi55** [comment]
I tried, there is no image on the panel.

**Comment by board707** [comment]
It is what I expected...
Unfortunately, this panel will not be supported until someone other can run it with Arduino.

**Comment by funnymind** [comment]
Hi @board707, I have similar panels now, I saw that you were ready to do some tests on them, if you still don't mind then I'm ready.
