### ISSUE TITLE
STM32CubeIDE 

### ISSUE THREAD

**Issue by KULCU** [board707/DMD_STM32#93]
STM32CubeIDE
I have a client project that I'm developing. I have a lot of environmental components in the project. Our customer wants to add P5 led panel to my project. We want to use DMD STM32.

DMD STM32 has too much Arduino dependency. How can I use the DMD STM32 project as an STM32 project to STM32CubeIDE without Arduino dependencies?

**Comment by board707** [comment]
Hi
The library written on Arduino environment and focused to Arduino users. It based on Rodger Clark's Arduino_STM32 project.

Theoretically, it can be ported to a CubeIDE, but I don’t see any real point in this. There are several other examples on the Internet of working with HUB75 matrices in a CubeIDE.
WBR, Dmitry
